### ISSUE TITLE
Check repository user name and password as late as possible

### ISSUE THREAD

**Issue by hvisser** [vanniktech/gradle-maven-publish-plugin#11]
I'd prefer if the plugin would check the presence of the repo username and password as late as possible, and not at configure time. Reason for this is that I'd like to supply my password when releasing only, without having to set permanently in the (global) `gradle.properties` or environment variables.

When I don't supply either username or password now, the plugin will error at configure time.

**Comment by vanniktech** [comment]
This should have been fixed with 0.3.0. Can you try that version?

**Comment by hvisser** [comment]
I'm using 0.3.0, and without any config the project won't configure.

`Please configure repositoryUsername via mavenPublish.repositoryUsername or alternatively set the Gradle / System environment variable SONATYPE_NEXUS_USERNAME`

Hitting the checks in https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/groovy/com/vanniktech/maven/publish/MavenPublishPlugin.groovy#L36

**Comment by vanniktech** [comment]
Does using 0.2.0 work? 0.3.0 changed something in that regard. 

I might as well just remove those checks all together if they're causing problems.

**Comment by vanniktech** [comment]
Pushed 0.4.0 out

**Comment by vanniktech** [comment]
Pushed 0.4.0 out

**Comment by hvisser** [comment]
`0.4.0` does not give me errors any more without config. Haven't tried to push anything yet though ;)
