### ISSUE TITLE
Must be applied at the end of a file for multiplatform projects

### ISSUE THREAD

**Issue by JakeWharton** [vanniktech/gradle-maven-publish-plugin#122]
Otherwise artifacts are not seen. For example, a MPP project targeting `jvm()` will find its jar omitted from upload unless the plugin is applied after the `kotlin` block.

**Comment by gabrielittner** [comment]
Is the project where you saw it public?

**Comment by JakeWharton** [comment]
Yep. I'll push the branch when I get home.

**Comment by JakeWharton** [comment]
https://github.com/JakeWharton/confundus/commit/21ce17f603f3ea83b83ff3919d26d8ba2347080e#diff-8faa9a41be9d0326345ee182271d98f8R26-R28

When `apply` is moved to the top of that file, run `check` and `build/localMaven/../confundus-api-jvm/` will be missing a jar.

**Comment by gabrielittner** [comment]
Thanks for the project. I think it's a weird bug in the Kotlin plugin. I removed gradle-maven-publish from you're project and just tried to use plain maven publish.

This does not work. It's essentially what this plugin does, since we need to wait until after evaluation to know about legacy mode.
```
apply plugin: 'org.jetbrains.kotlin.multiplatform'

afterEvaluate {
  apply plugin: "maven-publish"
  publishing {
      repositories {
          maven {
              url = "${rootProject.buildDir}/localMaven"
          }
      }
  }
}


group = "com.jakewharton.confundus"
version = "1.2.0"

kotlin {
  js()
  jvm()

  sourceSets {
    commonMain {
      dependencies {
        api deps.kotlin.stdlib.common
      }
    }
    jsMain {
      dependencies {
        api deps.kotlin.stdlib.js
      }
    }
    jvmMain {
      dependencies {
        api deps.kotlin.stdlib.jdk
      }
    }
  }
}
```

However this does work:
```
apply plugin: 'org.jetbrains.kotlin.multiplatform'

group = "com.jakewharton.confundus"
version = "1.2.0"

kotlin {
  js()
  jvm()

  sourceSets {
    commonMain {
      dependencies {
        api deps.kotlin.stdlib.common
      }
    }
    jsMain {
      dependencies {
        api deps.kotlin.stdlib.js
      }
    }
    jvmMain {
      dependencies {
        api deps.kotlin.stdlib.jdk
      }
    }
  }
}

afterEvaluate {
  apply plugin: "maven-publish"
  publishing {
      repositories {
          maven {
              url = "${rootProject.buildDir}/localMaven"
          }
      }
  }
}
```

Both cases work without `afterEvaluate`. So it seems like the issue occurs when `maven-publish` is applied in an `afterEvaluate` between the mpp plugin and the kotlin block, but it's fine if it's applied immediately or in an `afterEvaluate` after the kotlin block. I will investigate a bit more tomorrow and then probably open a ticket on YouTrack.

**Comment by gabrielittner** [comment]
Filed https://youtrack.jetbrains.com/issue/KT-37659

**Comment by vanniktech** [comment]
Thanks for investigating @gabrielittner.

Can we close this issue then?

**Comment by gabrielittner** [comment]
I think it makes sense to keep it open for visibility. We can close it when either it's fixed on Kotlin side or when we remove legacy mode which allows us to apply `maven-publish` immediately.

**Comment by vanniktech** [comment]
@gabrielittner legacy move was removed, which means we close now, right?

**Comment by gabrielittner** [comment]
Yes, everything should be working now regardless of where it is applied.
