### ISSUE TITLE
Gradle plugin upload missing sources and javadoc jars for central

### ISSUE THREAD

**Issue by ZacSweers** [vanniktech/gradle-maven-publish-plugin#125]
It seems that these need to be present on the ancillary artifact for central upload to work.

![image](https://user-images.githubusercontent.com/1361086/77836357-e81d7b00-712b-11ea-9a00-3ef5374d3aec.png)

![image](https://user-images.githubusercontent.com/1361086/77836360-eb186b80-712b-11ea-9678-9f5f410e60af.png)

![image](https://user-images.githubusercontent.com/1361086/77836361-ee135c00-712b-11ea-80e9-4e851f82cdca.png)

**Comment by vanniktech** [comment]
Which version of the plugin are you using?

**Comment by gabrielittner** [comment]
#126 should fix it. After that is merged I will test it with the snapshot to be sure.

**Comment by gabrielittner** [comment]
Tried out the just published snapshot and was able to close the repository successfully:
<img width="812" alt="Screenshot 2020-03-29 at 21 27 25" src="https://user-images.githubusercontent.com/1358105/77858476-2ab28680-7204-11ea-8f9e-03814dfd467c.png">

**Comment by ZacSweers** [comment]
This works on the 0.11.0 snapshot now 👍
