### ISSUE TITLE
Repository release failure after closing

### ISSUE THREAD

**Issue by ZacSweers** [vanniktech/gradle-maven-publish-plugin#128]
I get this exception when it tries to release the repository. Current status when I check is "closed", so seems like there's maybe some race condition

![image](https://user-images.githubusercontent.com/1361086/77859139-ab0dc300-71d5-11ea-94b1-d0d2cfbefa9b.png)

**Comment by gabrielittner** [comment]
cc @martinbonnin since you wrote the task

**Comment by martinbonnin** [comment]
I'll dogfood that in apollo-android to see if I can somehow reproduce. 

@ZacSweers did you end up having to manually release the repo or was it ok after calling `closeAndReleaseRepository` ?

**Comment by ZacSweers** [comment]
I had to manually release it

**Comment by vanniktech** [comment]
I wanted to release a new version with #126
Let's wait until this one is resolved too?

**Comment by ZacSweers** [comment]
Since this one isn't a show stopper, I wouldn't mind a 0.10.1 now and just add 0.10.2 later since this one I less obvious
