### ISSUE TITLE
Multi module release could not found the dependencies version

### ISSUE THREAD

**Issue by blling** [vanniktech/gradle-maven-publish-plugin#13]
When i deployed a multi module project, seems the submodule could not found the dependence version, error as follows:
![image](https://user-images.githubusercontent.com/26540808/42255060-6ce8197e-7f7c-11e8-85ab-913c578ea316.png)

My repo is [here](https://github.com/dxee/dject.git)

**Comment by vanniktech** [comment]
This can happen when using the parallel feature from Gradle. I think this can even happen when using the Daemon. I upload my libs using `./gradlew uploadArchives --no-daemon --no-parallel`

**Comment by blling** [comment]
Other jar from the maven center include pom info in the `META-INF`, but this plugin did not package it into my jar, maybe that is the problem? 

Other jar like this:
![image](https://user-images.githubusercontent.com/26540808/42270621-e7704d88-7fb3-11e8-8daf-48688235182b.png)

**Comment by vanniktech** [comment]
Hmmm interesting. Did you use the other Gradle maven publish script or is this your first time?

**Comment by blling** [comment]
I just use `gradle-maven-publish-plugin` for the first publish, Repo is here https://github.com/dxee/dject.git.

**Comment by vanniktech** [comment]
I'll take a look once I've got some more time.

**Comment by blling** [comment]
I publish a new version, it seems OK.:)
