### ISSUE TITLE
Is `MavenPublishPlugin` running too early?

### ISSUE THREAD

**Issue by eliekarouz** [vanniktech/gradle-maven-publish-plugin#131]
Version 0.11.1:

I am getting this error when syncing project when I apply the `plugin`:

```
A problem occurred configuring project ':XXX'.
SoftwareComponentInternal with name 'release' not found.
```
The error is caused by this [line](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/c695a11df4d42e1aebb2a8d6ef4c84ec3e95ece2/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishConfigurer.kt#L182)

It looks like it is trying to configure the publish plugin before the `variants`/`components` are created. That's why it's not finding the `release` component.

Here is the gradle file:

```gradle
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.0"
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 29
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

apply from: rootProject.file('gradle/gradle-mvn-push.gradle')
```

The `gradle-mvn-push.gradle` contains:
```gradle
apply plugin: 'com.vanniktech.maven.publish'

group = GROUP
version = VERSION_NAME
```

Could it be I have something wrong with the config?
Thanks

**Comment by vanniktech** [comment]
What Android Gradle Plugin version are you using?

**Comment by eliekarouz** [comment]
Had to disable legacy mode to fix the problem

```gradle
mavenPublish {
  useLegacyMode = !project.plugins.hasPlugin('org.jetbrains.kotlin.multiplatform')
}
```
