### ISSUE TITLE
Kotlin Gradle DSL: configuration

### ISSUE THREAD

**Issue by petersamokhin** [vanniktech/gradle-maven-publish-plugin#132]
Hello!
Sample configurations using Kotlin Gradle DSL would be useful.

**Comment by vanniktech** [comment]
@ZacSweers aren't you on the Kotlin train and give some sample?

**Comment by ZacSweers** [comment]
Yeah here's an example: https://github.com/slackhq/keeper/blob/master/keeper-gradle-plugin/build.gradle.kts#L69-L74

**Comment by vanniktech** [comment]
Thanks!
