### ISSUE TITLE
POM_INCEPTION_YEAR not implemented

### ISSUE THREAD

**Issue by benjamin-bader** [vanniktech/gradle-maven-publish-plugin#134]
The readme indicates that this plugin uses a config property `POM_INCEPTION_YEAR`, but on inspection it doesn't seem like anything in the code actually uses this property.  I noticed this when migrating a project from its old `gradle-mvn-push.gradle` file to this plugin, and the pom no longer has that field.

Not really a dealbreaker - I'm not sure who even cares about that pom field - but noteworthy nonetheless.

Would you be open to a PR implementing this?  Seems pretty simple to add, if desired.

**Comment by gabrielittner** [comment]
This seems like an oversight. Definitely happy about a pr to fix this
