### ISSUE TITLE
Deprecate targets API

### ISSUE THREAD

**Issue by gabrielittner** [vanniktech/gradle-maven-publish-plugin#137]
We should deprecate the API to set create targets.

This is what we have:
```
mavenPublish {
  targets {
    myRepository {
      releaseRepositoryUrl = ""
      snapshotRepositoryUrl = ""
      repositoryUsername = ""
      repositoryPassword = ""
    }
  }
}
```

This is the standard Gradle API:
```
publishing {
    repositories {
        maven {
            url = ""
            credentials {
                username ""
                password ""
            }
        }
    }
}
```
The only advantage of our API is that we automatically switch between release and snapshot repository, but I think that's fine for additionally configured repositories. 

For our current defaults: We can and should still setup Sonatype OSS by default. Same behavior as right now with automatically switching between release and snapshot repositories. We can have a flag in our extension to disable adding it. The default maven local target can be removed, because Gradle automatically creates `publishToMavenLocal` and `publish<PubName>PublicationToMavenLocal` tasks.

As part of this I would also deprecate our `uploadArchives`, `installArchives`, `uploadArchivesRepoName` task aliases. There is no reason not to use `publish`, `publishAllPublicationsTo<RepositoryName>Repository` and `publishToMavenLocal` directly.

**Comment by vanniktech** [comment]
You'd still be able to push to multiple / different repositories (bintray, mavenCentral) etc, right?

**Comment by gabrielittner** [comment]
Yes, you just configure them through Gradle APIs instead of our own.
