### ISSUE TITLE
Add disableAutomaticPublicationCreation flag

### ISSUE THREAD

**Issue by gabrielittner** [vanniktech/gradle-maven-publish-plugin#138]
Currently we have a lot of magic going on behind the scenes which makes it hard to deviate from the standard use cases. If the new `disableAutomaticPublicationCreation` flag is enabled we don't create any publication and don't create set up sources, javadoc/dokka tasks by default.

How manual configuration would look like:
`java`, `java-library`
```
publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}

java {
  withSourcesJar()
  withJavadocJar()
}
```

`java-gradle-plugin`
```
java {
  withSourcesJar()
  withJavadocJar()
}
```

`com.android.library`
```
afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("maven") {
                from(components["release"])
            }
        }
    }
}

// new API by us until AGP offers something, exact name TBD
androidPublishCompat {
  withSourcesJar()
  withJavadocJar()
}
```

`org.jebtrains.kotlin.multiplatform`
```
// new API by us until Kotlin offers something, exact name TBD
kotlinMultiplatformPublishCompat {
  // sources jar already set up by default
  withJavadocJar()
}
```

As an example for something that wasn't supported directly before: `com.github.johnrengelman.shadow`
```
publishing {
    publications {
        create<MavenPublication>("maven") { publication ->
            project.shadow.component(publication)
        }
    }
}

java {
  withSourcesJar()
  withJavadocJar()
}
```

### What this plugin still does when the flag is on
- configure the pom for all publications (this would be a general behavior change, for java-library and Android, we're currently just touching the publication we create)
- configure signing
- some compatibility things like adding an empty sources jar to the `kotlinMultiplatform` publication until those things are fixed in the respective upstream repository

This generally brings us into the direction of just augmenting the default Gradle/AGP/Kotlin plugins with missing parts until they catch up, plus providing some nice defaults (maven central publishing, signing) and nicer configuration (pom through gradle properties).

**Comment by vanniktech** [comment]
Sounds good!

**Comment by gabrielittner** [comment]
Obsoleted by #173
