### ISSUE TITLE
SoftwareComponentInternal with name 'release' not found

### ISSUE THREAD

**Issue by saket** [vanniktech/gradle-maven-publish-plugin#151]
I’m trying to add this plugin to my project but I'm running into this error. Does this look familiar to anyone?
Here's my branch: https://github.com/saket/InterceptibleResources/commit/f697f98b3ec5734867f3790dfc5235850d71d22f

```gradle
A problem occurred configuring project ':interceptor'.
> SoftwareComponentInternal with name 'release' not found.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':interceptor'
Caused by: org.gradle.api.UnknownDomainObjectException: SoftwareComponentInternal with name 'release' not found.
	at com.vanniktech.maven.publish.MavenPublishConfigurer.configureAndroidArtifacts(MavenPublishConfigurer.kt:152)
	at com.vanniktech.maven.publish.MavenPublishPlugin.configurePublishing(MavenPublishPlugin.kt:100)
```

**Comment by gabrielittner** [comment]
Can you try applying the publish plugin with `apply plugin` instead of the `plugins` block. 

I think we have the general issue that our internal afterEvaluate runs before AGP's afterEvaluate when the publish plugin gets applied first

**Comment by saket** [comment]
You're referring to this right?

```gradle
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath 'com.vanniktech:gradle-maven-publish-plugin:0.12.0'
  }
}

apply plugin: "com.vanniktech.maven.publish"
```

This gives me the same error.

**Comment by gabrielittner** [comment]
Yes, but with the `apply plugin: "com.vanniktech.maven.publish"` being in `interceptor/build.gradle` after the other applies.

So
```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: "com.vanniktech.maven.publish"
```

**Comment by gabrielittner** [comment]
I tried it locally and it seems to fix the issue.

We should still improve this inside the plugin though.

**Comment by saket** [comment]
Awesome, this works thank you!

**Comment by benjamin-bader** [comment]
For anyone who hits this - I just ran into this error building an old project that hadn't been touched in a year or more.  It turns out that it was using AGP 3.5.0, and this 'release' configuration apparently wasn't added until version 3.6.0.  Bumping the AGP version resolved it.
