### ISSUE TITLE
Feature request: Gradle task to upload snapshot version

### ISSUE THREAD

**Issue by anggrayudi** [vanniktech/gradle-maven-publish-plugin#153]
We know that `uploadArchives` can upload stable and snapshot versions of the library just by changing the version name suffix. But I am facing an issue where I need to distinguish the Gradle task into:
* Upload snapshot version.
* Upload stable version. This version wont have suffix `-SNAPSHOT` of course.

So, instead of renaming `VERSION_NAME` each time we want to upload snapshots, we can write `VERSION_NAME` once in `gradle.properties`. Let's say `VERSION_NAME=1.2.5`. Whenever we want to upload snapshot version, we can append suffix `-SNAPSHOT` to the version name by executing a Gradle task. Thus it is simpler. Suppose that we have the following Gradle tasks:
* `uploadArchives` --> For stable version
* `uploadSnapshotArchives` --> For snapshot version. This task will append suffix `-SNAPSHOT` to the version name.

**Comment by gabrielittner** [comment]
You should be able to run `./gradlew uploadArchives -PVERSION_NAME=1.2.5-SNAPSHOT`

**Comment by anggrayudi** [comment]
How do we read `VERSION_NAME` defined in `gradle.properties` and append suffix `-SNAPSHOT` using that command line?

It is better if we wrap this command into a new Gradle task.

**Comment by anggrayudi** [comment]
That command line did not work. You can try it.

**Comment by gabrielittner** [comment]
The property should work, at least it works locally for me and it's how Gradle properties behave.

There is another way to get a separate task:

```
publishing {
    repositories {
        maven {
            name = "snapshots"
            url = "url to snapshot repo"
        }
    }
}
```

The you will get a task called `publishAllPublicationToSnapshotsRepository`.

**Comment by anggrayudi** [comment]
Didn't work @gabrielittner . Got this error message:

```
Execution failed for task ':storage:publishMavenPublicationToSnapshotsRepository'.
> Failed to publish publication 'maven' to repository 'snapshots'
   > Could not PUT 'https://oss.sonatype.org/content/repositories/snapshots/com/anggrayudi/storage/0.4.4/storage-0.4.4.aar'. Received status code 401 from server: Unauthorized
```
