### ISSUE TITLE
Feature request: support Gradle's new Provider<PasswordCredentials> API

### ISSUE THREAD

**Issue by ZacSweers** [vanniktech/gradle-maven-publish-plugin#154]
Talked with @gabrielittner about this, I plan to submit a PR. Creating an issue so I can link it in a TODO in our own code :) 

```kotlin
val credentials = providers.credentials(PasswordCredentials::class, "SonatypeNexusUsername")

mavenPublish {
  targets {
    getByName("uploadArchives") {
      credentials(credentials)
      // Or credentials("SonatypeNexusUsername")
    }
  }
}
```

**Comment by vanniktech** [comment]
Sounds good, you two should take over this plugin.

**Comment by gabrielittner** [comment]
With #213 NexusOptions is deprecated. We're using the credentials API to configure the publishing repository and are reusing the same properties for our `closeAndReleaseRepository` task
