### ISSUE TITLE
POM_ARTIFACT_ID not found when the plugin is applied to subprojects inside the root build.gradle

### ISSUE THREAD

**Issue by Egorand** [vanniktech/gradle-maven-publish-plugin#158]
I'm trying to migrate from the setup where every subproject is applying the plugin using the `plugins` block:

```kotlin
plugins {
  id("com.vanniktech.maven.publish") version versions.mavenPublish
}
```

to applying the plugin to every subproject inside the root build.gradle's `subprojects` block:

```kotlin
plugins {
  id("com.vanniktech.maven.publish") version versions.mavenPublish apply false
}

subprojects {
  ...
  apply(plugin = "com.vanniktech.maven.publish")
}
```

This worked fine in 0.8.0, but since then the plugin complains about `POM_ARTIFACT_ID` property missing. This property is declared in every subproject's `gradle.properties`, however it's missing from the root level `gradle.properties`, since the root is not published as an artifact. The workaround is to add this property, however it isn't really needed for practical purposes.

Not sure what the right approach here is, maybe resolving properties at execution time vs configuration time?

Here's the branch that upgrades the plugin and introduces the issue: https://github.com/square/kotlinpoet/tree/egorand/200905/dokka-1.4.0

**Comment by gabrielittner** [comment]
I think you just have a typo in this [line](https://github.com/square/kotlinpoet/compare/egorand/200905/dokka-1.4.0#diff-392475fdf2bc320d17762ed97109a121R55) and it should be `kotlinpoet-metadata-specs-tests` (missing s at the end).

**Comment by Egorand** [comment]
That was it, sorry!
