### ISSUE TITLE
Plugin with id 'org.jetbrains.dokka' not found

### ISSUE THREAD

**Issue by anggrayudi** [vanniktech/gradle-maven-publish-plugin#162]
<img width="892" alt="Screen Shot 2020-09-08 at 16 04 53" src="https://user-images.githubusercontent.com/12292380/92456378-09ab8400-f1ed-11ea-9138-b00c18cae24e.png">

This error occurs on `0.13.0` only. On `0.12.0` this library works smoothly.

**Comment by gabrielittner** [comment]
If your project uses Kotlin you now need to explicitly add dokka to your buildscript.

**Comment by anggrayudi** [comment]
Any reason why we should add Dokka on version `0.13.0`, @gabrielittner ?

**Comment by gabrielittner** [comment]
We used to depend on it directly and pull it in for everyone. That can cause versioning issues of a project wants to use a different version and for Java projects it would download dokka without using it. This makes it more explicit.
