### ISSUE TITLE
Connection timeouts to Sonatype

### ISSUE THREAD

**Issue by chrisbanes** [vanniktech/gradle-maven-publish-plugin#170]
I'm not sure this is a bug as such, but figured I'd raise this.

I've been seeing a lot of connection timeouts lately while uploading to Sonatype, especially from less-powerful machines (i.e. from GitHub Actions).

I _think_ the issue is that this plugin opens up a connection to Sonatype, and _then_ runs Dokka/assemble, waiting for all of the artifacts to upload. Dokka 1.4.0+ is pretty slow, so we can easily timeout the connection (which I assume is ~30 seconds). This is just from my observations though, it might not actually be that.

I have a workaround in https://github.com/chrisbanes/accompanist/pull/146, which basically runs Dokka + assemble _before_ `uploadArchives`: `./gradlew assembleRelease dokkaHtml uploadArchives`. 

Maybe the task dependency graph for `uploadArchives` could be tweaked to achieve similar?

Here's a example log:

```
> Task :insets:preBuild UP-TO-DATE
> Task :insets:preDebugBuild UP-TO-DATE
> Task :insets:compileDebugRenderscript NO-SOURCE
> Task :insets:generateDebugResValues FROM-CACHE
> Task :insets:generateDebugResources UP-TO-DATE
> Task :insets:packageDebugResources FROM-CACHE
> Task :insets:parseDebugLocalResources FROM-CACHE
> Task :insets:processDebugManifest FROM-CACHE
> Task :insets:generateDebugRFile FROM-CACHE
> Task :insets:preReleaseBuild UP-TO-DATE
> Task :insets:compileReleaseRenderscript NO-SOURCE
> Task :insets:generateReleaseResValues FROM-CACHE
> Task :insets:generateReleaseResources UP-TO-DATE
> Task :insets:packageReleaseResources FROM-CACHE
> Task :insets:parseReleaseLocalResources FROM-CACHE
> Task :insets:processReleaseManifest FROM-CACHE
> Task :insets:generateReleaseRFile FROM-CACHE

> Task :insets:dokkaHtml
Dokka 1.4.* is an alpha project
Initializing plugins
Creating documentation models
Transforming documentation model before merging
Merging documentation models
Transforming documentation model after merging
Creating pages
Transforming pages
Rendering


> Task :insets:dokkaHtml FAILED


FAILURE: Build failed with an exception.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

* What went wrong:
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
129 actionable tasks: 32 executed, 97 from cache
Execution failed for task ':insets:dokkaHtml'.
> java.net.SocketTimeoutException: Read timed out
```

**Comment by vanniktech** [comment]
Sounds reasonable, yes.

**Comment by JakeWharton** [comment]
Another mitigation in the time being is to use an internal property to up the timeout.

I've set
```
systemProp.org.gradle.internal.http.socketTimeout=120000
```
which quadruples the timeout.

**Comment by gabrielittner** [comment]
`uploadArchives` is just an alias for Gradle's `publishAllPublicationsTo[...]Repository` task. The only thing we do is telling Gradle which tasks are an input for that, so this would be an issue on Gradle's side. I'd prefer not to do anything additional here. We are generally trying to just bridge gaps in Gradle's/Kotlin's/Android's publishing setup. While this could be considered such a gap, a fix would be brittle and could break with every Gradle release.

The next release will just publish an empty javadoc jar when you don't apply the Dokka plugin yourself. That could be used as another mitigation.
