### ISSUE TITLE
Eliminate property file usage

### ISSUE THREAD

**Issue by JakeWharton** [vanniktech/gradle-maven-publish-plugin#171]
This seems to be a holdover from Chris' script, but it feels very out-of-place in modern Gradle.

Gradle has built-in mechanisms for specifying the group, artifact, and version. You're already required to use them in order to get peer dependencies working properly. These canonical sources should be used rather than a properties file.

Specifying all of the additional information for a POM feels like it should be done in an extension. This would allow project-local specification of name and description while using `subprojects { plugins.withId(..) { .. } }` for shared configuration such as URLs and developer.

**Comment by ZacSweers** [comment]
we're planning to do an API revamp with breaking changes and raise the min API version, so this would be a good candidate for that 👍
