### ISSUE TITLE
Android release buildType

### ISSUE THREAD

**Issue by OlegTranzzo** [vanniktech/gradle-maven-publish-plugin#175]
I want to publish android library. 
I call `./gradlew uploadArchives --no-daemon --no-parallel`
But the build takes debug buildType, how to set up release buildType?

**Comment by gabrielittner** [comment]
Can you share the project? Our default is to publish the release variant.

**Comment by OlegTranzzo** [comment]
I figured out the release is being picked. But I need to hide the sources.
How do I disable source generation?

**Comment by gabrielittner** [comment]
Right now you can't, you can follow #164 for that
