### ISSUE TITLE
Error to publish KMM library (1.4.30) to mavenLocal repo

### ISSUE THREAD

**Issue by francismariano** [vanniktech/gradle-maven-publish-plugin#184]
Hello guys.

I am trying to publish to mavenLocal a KMM library. The multiplatform plugin version is 1.4.30

With the kotlin multiplatform to 1.4.30, the task ':core:publishKotlinMultiplatformPublicationToLocalRepository'  fails.
```
* What went wrong:
Execution failed for task ':core:publishKotlinMultiplatformPublicationToLocalRepository'.
> Failed to publish publication 'kotlinMultiplatform' to repository 'local'
   > Invalid publication 'kotlinMultiplatform': multiple artifacts with the identical extension and classifier ('jar', 'sources').
```
With the version 1.4.20 (multiplatform) the plugin works fine

The last release version is 0.13.0 but I see that you fix somethings related to kotlin 1.4.30 and gradle 6.8 plugin. Do you think these fixes also fixing the issue described above?

**Comment by gabrielittner** [comment]
Hi, yes this will be fixed in 0.14.0 which will be out soon.

**Comment by francismariano** [comment]
ok, thank you

**Comment by gabrielittner** [comment]
It's out now
