### ISSUE TITLE
Can't upload snaphot builds to Sonatype after switch to builds that require Kotlin 1.4.30

### ISSUE THREAD

**Issue by kirill-grouchnikov** [vanniktech/gradle-maven-publish-plugin#185]
Using these dependencies:

```
    dependencies {
        classpath("org.jetbrains.compose:compose-gradle-plugin:0.3.0-build152")
        classpath(kotlin("gradle-plugin", version = "1.4.30"))
        classpath("com.vanniktech:gradle-maven-publish-plugin:0.13.0")
        classpath("org.jetbrains.dokka:dokka-gradle-plugin:1.4.20")
    }
```

and running `gradlew uploadArchives`

```
> Task :bitmapfilter:dokkaHtml
Dokka 1.4.* is an alpha project
Initializing plugins
Validity check
Creating documentation models
Transforming documentation model before merging
Merging documentation models
Transforming documentation model after merging
Creating pages
Transforming pages
Rendering


> Task :bitmapfilter:publishKotlinMultiplatformPublicationToMavenRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bitmapfilter:publishKotlinMultiplatformPublicationToMavenRepository'.
> Failed to publish publication 'kotlinMultiplatform' to repository 'maven'
   > Invalid publication 'kotlinMultiplatform': multiple artifacts with the identical extension and classifier ('jar', 'sources').
```

I've opened this at https://github.com/JetBrains/compose-jb/issues/365 but maybe it's an issue with this plugin

**Comment by gabrielittner** [comment]
The issue was on our side. We had a workaround for Kotlin not creating a sources jar for one of the artifact, which broke when they fixed in in Kotlin 1.4.30. We just release version 0.14.0 which fixes this issue

**Comment by kirill-grouchnikov** [comment]
Oh, great news. Let me try.

**Comment by kirill-grouchnikov** [comment]
Unrelated (probably another issue needed to track):

```
The property SONATYPE_NEXUS_USERNAME is deprecated. Use mavenCentralRepositoryUsername instead.
The property SONATYPE_NEXUS_USERNAME is deprecated. Use mavenCentralRepositoryPassword instead.
Adding additional targets through this API is deprecated. Use the default Gradle APIs to add additional targets/repositorieshttps://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories
Adding additional targets through this API is deprecated. Use the default Gradle APIs to add additional targets/repositorieshttps://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories
```

I don't have that property specified anywhere. The second one should probably be PASSWORD instead of USERNAME. And some spacing needed in the last two lines

**Comment by kirill-grouchnikov** [comment]
Verified that uploading to Sonatype staging works with 0.14.0.

**Comment by gabrielittner** [comment]
Thanks for that, I've addressed most of that in here #187

The only thing I'm not sure about is is why you get the first 2 lines if `SONATYPE_NEXUS_USERNAME` and `SONATYPE_NEXUS_PASSWORD` are not specified anywhere. Could you check if they are also not in your `~/.gradle/gradle.properties`. The warning is printed when Gradle returns a non null value for the property.

**Comment by kirill-grouchnikov** [comment]
Not seeing those anywhere in https://github.com/kirill-grouchnikov/aurora

**Comment by kirill-grouchnikov** [comment]
Maybe I do have them in the "secret" local properties - since I use them in another project that isn't using this plugin

**Comment by kirill-grouchnikov** [comment]
Yes, I have them in `.gradle/gradle.properties` for another project, so that's on my side.

**Comment by gabrielittner** [comment]
Then from the next release of this plugin you probably just need to duplicate them in that file with the new names. I'll make sure that we don't fail when finding the old properties, so that you don't need to change anything in your other project.

**Comment by kirill-grouchnikov** [comment]
Actually my memory might not serve me well. I'm using https://github.com/bmuschko/gradle-nexus-plugin in the other project, and that expects a different pair - https://github.com/bmuschko/gradle-nexus-plugin#credentials

So I think I've had `SONATYPE_NEXUS_USERNAME` and `SONATYPE_NEXUS_PASSWORD` for this plugin.
