### ISSUE TITLE
CI build failing with Cannot perform signing task ':compiler-plugin-utils:signMavenPublication' because it has no configured signatory

### ISSUE THREAD

**Issue by rnett** [vanniktech/gradle-maven-publish-plugin#188]
See: https://github.com/rnett/compiler-plugin-utils/runs/1876894367?check_suite_focus=true

CI: https://github.com/rnett/compiler-plugin-utils/blob/main/.github/workflows/ci.yml

Gradle files are in the repo, I'm using version 0.14.0 of the plugin.

Things work fine locally, the only properties I'm defining in the system wide `gradle.properties` are the ones passed to the publish task.

**Comment by gabrielittner** [comment]
The linked repo isn't public. Did you set up signing like this? https://github.com/vanniktech/gradle-maven-publish-plugin#signing

**Comment by rnett** [comment]
Oops, it is now.  And yeah, that's exactly what I did, just passed as properties rather than in a file, which I wouldn't think matters.

**Comment by gabrielittner** [comment]
And locally signing works when you put he properties into the properties file? I can't see anything wrong. Can you maybe try `-P` instead of `-D`?

**Comment by gabrielittner** [comment]
Btw to simplify your setup, you can prefix environment variable with `ORG_GRADLE_PROJECT_` to get them automatically picked up as properties. So `ORG_GRADLE_PROJECT_mavenCentralRepositoryUsername` will get picked up as `mavenCentralRepositoryUsername`

**Comment by rnett** [comment]
Huh, `-P` worked, thanks.

**Comment by rnett** [comment]
Interestingly, `ORG_GRADLE_PROJECT_` did not work for signing configuration.
