### ISSUE TITLE
Provide more information in additional targets warning

### ISSUE THREAD

**Issue by kirill-grouchnikov** [vanniktech/gradle-maven-publish-plugin#190]
https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/kotlin/com/vanniktech/maven/publish/legacy/Targets.kt#L60 prints out:

```
Adding additional targets through this API is deprecated. Use the default Gradle APIs to add additional targets/repositorieshttps://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories
Adding additional targets through this API is deprecated. Use the default Gradle APIs to add additional targets/repositorieshttps://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories
```

Every time I do a local build (not publish, just the build) of https://github.com/kirill-grouchnikov/aurora

I have no idea what that means. Is there any additional info that line can print? It points to https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:repositories which has `publishing` blocks, but I don't have those blocks anywhere in my build scripts.

**Comment by gabrielittner** [comment]
Those two are false positives, sorry for that. It's reporting the 2 targets we're adding internally. The fix is in #187 together with the typos you reported yesterday. I'll do a 0.14.1 release with that.

**Comment by gabrielittner** [comment]
0.14.1 is out

**Comment by kirill-grouchnikov** [comment]
Confirmed that the warning messages are gone on my side with 0.14.1. Thanks for the quick fix!
