### ISSUE TITLE
0.14.1 closeAndReleaseRepository fails with "No value has been specified for property 'stagingRepository'"

### ISSUE THREAD

**Issue by akarnokd** [vanniktech/gradle-maven-publish-plugin#193]
The release process worked with 0.13.0 but after upgrading to 0.14.1, I get this error.

I can't find any documentation about what this `stagingRepository` is supposed to be.

https://github.com/ReactiveX/RxJava/runs/1892963986?check_suite_focus=true#step:11:28

Please advise.

**Comment by gabrielittner** [comment]
Sorry that is a bug on our side. You can workaround it by calling adding `--repository=empty`. I'll include a fix for this in 0.14.2

**Comment by gabrielittner** [comment]
Just published 0.14.2 which should fix the issue
