### ISSUE TITLE
Custom archive name

### ISSUE THREAD

**Issue by jendakol** [vanniktech/gradle-maven-publish-plugin#198]
Hello,
I'm trying to use your plugin to release my Scala app to Sonatype. Everything works except one small detail - I need a custom artifact name for each submodule with a dynamic generation (so specifying it in `gradle.properties` just doesn't work for me).  
I tried to use `archivesBaseName = "rabbitmq-client-api_$scalaVersion"` as with the previous release plugin (Bintray :roll_eyes:) but it doesn't work with this one. I digged into the code of yours and you have a fallback to `project.name` only - would it be possible to have another fallback from `POM_ARTIFACT_ID` property, the `archiveBaseName` in ideal case? I'd love to send you a PR but am unable to hack it...  
Thanks!

**Comment by gabrielittner** [comment]
I've opened an issue with Gradle for having something like `archivesBaseName` for `maven-publish`. https://github.com/gradle/gradle/issues/16967 As mentioned there everything we could do (and are already doing) in this area would be hacky and prone to break so I'd like to avoid creating an API for this on our side.
