### ISSUE TITLE
Version 0.14.0 fails when Dokka is not on the buildscript classpath

### ISSUE THREAD

**Issue by zach-klippenstein** [vanniktech/gradle-maven-publish-plugin#205]
Repro steps: 

1. Create gradle project. DO NOT configure dokka, esp do not include a `buildscript { dependencies { classpath … } }` entry for it.
2. Configure the gradle-maven-publish-plugin.
3. Attempt to publish to local repository.

You'll get this error:
```
* What went wrong:
An exception occurred applying plugin request [id: 'com.vanniktech.maven.publish']
> Failed to apply plugin 'com.vanniktech.maven.publish'.
   > Plugin with id 'org.jetbrains.dokka' not found.
```

**Comment by gabrielittner** [comment]
This is currently a requirement for Kotlin projects. In the past we had a direct dependency on it which might cause compatibility issues. We've changed that already to a `compileOnly` dependency but for now it's still required to be added by users. My plan is to either add an option to disable dokka or just completely remove the requirement in on of the next releases. Then Kotlin projects without dokka would just publish empty `javadoc` jars.

**Comment by zach-klippenstein** [comment]
> Then Kotlin projects without dokka would just publish empty javadoc jars.

That sounds like the behavior I would expect. Thanks for the heads up!

**Comment by gabrielittner** [comment]
The next release (0.15.0) will not apply the dokka plugin automatically anymore and will just publish an empty javadoc jar.
