### ISSUE TITLE
New domain of OSSRH

### ISSUE THREAD

**Issue by RikkaW** [vanniktech/gradle-maven-publish-plugin#206]
> As of February 2021, all new projects began being provisioned on https://s01.oss.sonatype.org/.

https://central.sonatype.org/pages/releasing-the-deployment.html

I found some hardcoded "oss.sonatype.org" and I don't know how to change through the project's .gradle files.

https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/kotlin/com/vanniktech/maven/publish/nexus/NexusOptions.kt#L41
https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishPlugin.kt#L30
https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishPlugin.kt#L35

**Comment by eygraber** [comment]
To work around this you need to override the repository that this plugin sets up (in your build.gradle):

```
publishing {
  repositories {
    maven {
      def releasesRepoUrl = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
      def snapshotsRepoUrl = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
      url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
      name = "mavenCentral"
      credentials(PasswordCredentials)
    }
  }
}
```

**Comment by eygraber** [comment]
Never mind, the above doesn't work (although I don't understand why).

**Comment by eygraber** [comment]
OK I was able to fix it by placing this block before applying the plugin:

```
ext {
  RELEASE_REPOSITORY_URL = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
  SNAPSHOT_REPOSITORY_URL = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
}
```

**Comment by gabrielittner** [comment]
Yes that should work for now, alternatively it should also work to put these 2 into `gradle.properties`. We'll have something in the next release to handle this better.

**Comment by PeekAndPoke** [comment]
A work-around that does it for me for now is this user `withType<MavenArtifactReposiroty>` instead of `maven`. 
This will not create a new repo but give you the existing ones. Then you have to filter out the "local" etc.

```
        withType<MavenArtifactRepository> {

            if (name == "local") {
                return@withType
            }

            println("------------------------------------------------------")
            println(url)

            val releasesRepoUrl = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
            val snapshotsRepoUrl = "https://s01.oss.sonatype.org/content/repositories/snapshots/"

            url = if (VERSION_NAME.endsWith("SNAPSHOT")) {
                uri(snapshotsRepoUrl)
            } else {
                uri(releasesRepoUrl)
            }

            println(url)
            println("------------------------------------------------------")

            credentials {
                username = mavenCentralRepositoryUsername
                password = mavenCentralRepositoryPassword
            }
        }

```

**Comment by nanodeath** [comment]
To round out @PeekAndPoke's great example, if you want the `closeAndReleaseRepository` task, you should add this:

```kotlin
mavenPublish {
    nexus {
        baseUrl = "https://s01.oss.sonatype.org/service/local/"
        repositoryUsername = mavenCentralRepositoryUsername
        repositoryPassword = mavenCentralRepositoryPassword
    }
}
```

**Comment by gabrielittner** [comment]
0.15.0 was just published and now has an API to switch to s01.oss.sonatype.org. You can find a description here https://github.com/vanniktech/gradle-maven-publish-plugin#where-to-upload-to
