### ISSUE TITLE
Cannot use 'mavenCentralRepositoryUsername' and 'mavenCentralRepositoryPassword' as env variables

### ISSUE THREAD

**Issue by colinrtwhite** [vanniktech/gradle-maven-publish-plugin#207]
Hi I'm migrating to `0.14.2` and it mentions [here](https://github.com/vanniktech/gradle-maven-publish-plugin#where-to-upload-to) in the readme that `mavenCentralRepositoryUsername` and `mavenCentralRepositoryPassword` can be provided as "Gradle properties or environment variables", however from [the code](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/f6c13c5330c83757a25f9e51ec558db0bb344fb3/src/main/kotlin/com/vanniktech/maven/publish/nexus/NexusOptions.kt#L47) it looks like they can only be provided as Gradle properties.

**Comment by gabrielittner** [comment]
Hi you can provide gradle properties as env vars by prefixing them with `ORG_GRADLE_PROJECT_`. So if you have `ORG_GRADLE_PROJECT_mavenCentralRepositoryUsername and `ORG_GRADLE_PROJECT_mavenCentralRepositoryPassword` they will match the wanted properties.

**Comment by colinrtwhite** [comment]
Sounds good, I added them using the prefix - thanks.

It might be worth updating the readme to mention this as I assumed I could migrate from `SONATYPE_NEXUS_USERNAME` -> `mavenCentralRepositoryUsername` directly since `SONATYPE_NEXUS_USERNAME` could be used as an environment variable without the prefix.
