### ISSUE TITLE
Java module using Kotlin for tests forced to use Dokka for javadocJar

### ISSUE THREAD

**Issue by JakeWharton** [vanniktech/gradle-maven-publish-plugin#211]
As far as I can tell the application of the Kotlin plugin unconditionally forces the Dokka plugin's addition which alters the behavior of JavadocJar task. My module is Java-only and needs the regular Javadoc generation to be preferred. Seems like similar behavior might occur for people who use Groovy solely for tests for things like Spock.

**Comment by gabrielittner** [comment]
I'm already working on changing this behavior for the next release 👍 we'll just use dokka if you apply the plugin yourself then. There will also be a no magic base plugin that offers some high level api to configure what you need

**Comment by gabrielittner** [comment]
0.15.0 is on it's way to central and does not apply dokka on it's own anymore
