### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by donmor** [vanniktech/gradle-maven-publish-plugin#214]
I got this error on uploadArchives:
```
Could not PUT 'https://oss.sonatype.org/service/local/staging/deploy/maven2/com/github/donmor/FileDialog/1.2.1/FileDialog-1.2.1.aar'. Received status code 403 from server: Forbidden
```
Is it the url in the plugin expired? They're now using https://s01.oss.sonatype.org instead.

**Comment by gabrielittner** [comment]
See the comments in #206 on how to use the s01 domain. We'll have a proper solution in the next release
