### ISSUE TITLE
Builds fail with error: 'SoftwareComponentInternal with name 'release' not found.'

### ISSUE THREAD

**Issue by gmale** [vanniktech/gradle-maven-publish-plugin#215]
Even running a `./gradlew clean` results in this error when there is no variant named "release."

I was able to get around this error by specifying the `androidVariantToPublish` but this exposes two related problems:

- This setting on the `mavenPublish` extension does not appear to be documented at all in the main README
- The error message could be more descriptive, given that it even prevents a `clean` from executing

**Comment by gmale** [comment]
The error message can be improved by [sanity checking the value that is used here](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/476d684501b9f9e8ed81d71c26a43b66071bc7f4/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishConfigurer.kt#L65)

**Comment by gmale** [comment]
@vanniktech added two examples to address the issues mentioned in the description. Let me know if they require any changes.

**Comment by gabrielittner** [comment]
Thanks for the prs 👍
