### ISSUE TITLE
How to fix "RELEASE_REPOSITORY_URL property is deprecated"?

### ISSUE THREAD

**Issue by dafi** [vanniktech/gradle-maven-publish-plugin#219]
Plugin version: 0.14.2
Gradle version: 6.6.1

I need to use the `https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/` url so inside my `gradle.properties` I set `RELEASE_REPOSITORY_URL` and everything works fine

Now I want to remove the deprecated properties `RELEASE_REPOSITORY_URL` and `SNAPSHOT_REPOSITORY_URL` and if I correctly understand following [Where to upload to](https://github.com/vanniktech/gradle-maven-publish-plugin#where-to-upload-to) I must replace them inside my android library `build.gradle` (not the root project) with:
The code do not use `SNAPSHOT_REPOSITORY_URL` only to make example simpler

```gradle
  publishing {
      repositories {
          maven {
              url = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
          }
      }
  }
```

But running `./gradlew publish --no-daemon --no-parallel` the url value is ignored falling back to `https://oss.sonatype.org`

May you tell me the correct way to remove the deprecated proeprties and how to use the correct "mode"?

**Comment by aamir-locus** [comment]
Refer this :- https://github.com/vanniktech/gradle-maven-publish-plugin/issues/221

**Comment by gabrielittner** [comment]
We will have something in the next release to switch to `s01.oss.sonatype.org` without using the deprecated properties. Please follow #206 for updates
