### ISSUE TITLE
Property-free configuration

### ISSUE THREAD

**Issue by JakeWharton** [vanniktech/gradle-maven-publish-plugin#223]
I would like to configure the entire details of publishing without using properties. I am currently working on a project which uses `includeBuild` but is conceptually a single project. Sharing properties between entire Gradle projects is much harder than sharing via `.gradle` files which can be included and whose logic can be more dynamic.

**Comment by gabrielittner** [comment]
We will have something in the next release for this, the majority of it is already on master and I'm hoping to have enough time this week to finish the rest

**Comment by gabrielittner** [comment]
0.15.0 containing this is on it's way to central. The API is described here https://github.com/vanniktech/gradle-maven-publish-plugin#base-plugin the POM specific part works also when using the main plugin not just the base plugin. Only note is that it's currently still marked as incubating, but I don't expect the `pom` method to change as we're just exposing Gradle's API through that.
