### ISSUE TITLE
Signature validation failed when passing RELEASE_SIGNING_ENABLED=false

### ISSUE THREAD

**Issue by aamir-locus** [vanniktech/gradle-maven-publish-plugin#224]
I am trying to release the artefacts by disabling the signing but the error encountered when I try to release my package.

`./gradlew publish --no-daemon --no-parallel -PRELEASE_SIGNING_ENABLED=false` 

![image](https://user-images.githubusercontent.com/76806206/114688439-52528f00-9d32-11eb-8968-5cf10d4bce1e.png)

**Comment by gabrielittner** [comment]
Maven central does not allow to release unsigned artifacts. The option to disable signing on our side is only meant for development purposes.
