### ISSUE TITLE
Tasks created by plugin after project evaluation can't be modified

### ISSUE THREAD

**Issue by 3flex** [vanniktech/gradle-maven-publish-plugin#225]
As far as I can tell there's no way to do this to directly access the tasks provided by this plugin to provide custom configuration:

```groovy
tasks.named("sourcesJar").configure { }
```

Because the tasks created by this plugin are only created once the project is evaluated. The only option is

```groovy
tasks.withType(SourcesJar).configureEach { }
```

which works, but is more of a blunt instrument for task customisation.

The use case is applying `duplicatesStrategy = DuplicatesStrategy.INCLUDE` to the sourcesJar task to reflect the old default behaviour of Gradle, without which the project I'm working on will not currently build on Gradle 7.

**Comment by gabrielittner** [comment]
Unfortunately with the way the plugin is working we can't create these tasks until project evaluation. You could give our new base plugin a try https://github.com/vanniktech/gradle-maven-publish-plugin#base-plugin With that the tasks will be registered when you call `configure` on the `mavenPublishing` extension, so you should be able to modify them right afterwards
