### ISSUE TITLE
Operation timed out (Read failed)

### ISSUE THREAD

**Issue by marandaneto** [vanniktech/gradle-maven-publish-plugin#232]
Hi, thanks for the lib :)

More like a question, I'm getting `Operation timed out (Read failed)` quite often and I'm not sure either if it's the plugin or MC itself.

Plugin: 0.14.2 (tried with 0.15.0 too)
Gradle: 6.8.3
OS: macOS 11.2.3

eg:

> Failed to publish publication 'maven' to repository 'maven'
   > Could not write to resource 'https://oss.sonatype.org/service/local/staging/deploy/maven2/io/sentry/sentry-spring/5.0.0-beta.1/sentry-spring-5.0.0-beta.1-javadoc.jar.asc'.
      > Operation timed out (Read failed)

it's a repo with 12 modules so not sure if this would be a problem (like racy conditions or something like that).

I do use `--no-daemon --no-parallel`

I also have `systemProp.org.gradle.internal.http.socketTimeout=120000` in my `gradle.properties`, increasing time does not help either.

tried to use some other Gradle properties as https://quotidian-ennui.github.io/blog/2020/06/05/gradle-timeout-fun/ says.

maybe related to https://github.com/vanniktech/gradle-maven-publish-plugin/issues/170

any ideas? thanks.

**Comment by marandaneto** [comment]
might be a coincidence but it always times out when executing `publishMavenPublicationToMavenRepository` for `*-sources.jar.asc` files

**Comment by marandaneto** [comment]
> 2021-04-29T13:08:11.610+0200 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Upload https://oss.sonatype.org/service/local/staging/deploy/maven2/io/sentry/sentry-log4j2/5.0.0-beta.1/sentry-log4j2-5.0.0-beta.1-javadoc.jar.asc' completed
> 2021-04-29T13:08:11.610+0200 [INFO] [org.gradle.api.internal.artifacts.repositories.transport.NetworkOperationBackOffAndRetry] Error in 'PUT https://oss.sonatype.org/service/local/staging/deploy/maven2/io/sentry/sentry-log4j2/5.0.0-beta.1/sentry-log4j2-5.0.0-beta.1-javadoc.jar.asc'. Waiting 1000ms before next retry, 2 retries left
> 2021-04-29T13:08:11.610+0200 [DEBUG] [org.gradle.api.internal.artifacts.repositories.transport.NetworkOperationBackOffAndRetry] Network operation failed
> org.gradle.api.resources.ResourceException: Could not write to resource 'https://oss.sonatype.org/service/local/staging/deploy/maven2/io/sentry/sentry-log4j2/5.0.0-beta.1/sentry-log4j2-5.0.0-beta.1-javadoc.jar.asc'.

logs are always like this, I know that the uploading is made by `Gradle` itself, but could it be a signing issue maybe so Maven returns an error? works for all the other packages within this Gradle project

**Comment by gabrielittner** [comment]
I don't think it's signing related as signing itself is just responsible for creating the files. The validation if the uploaded files are signed correctly happens when you close the repository on Sonatype.

> it's a repo with 12 modules so not sure if this would be a problem (like racy conditions or something like that).

Maybe you could try just running the publish task on the module that always fails to figure out if this is the case.

**Comment by marandaneto** [comment]
@gabrielittner I've tried, the same thing.
I've published the same project 20 days ago, everything worked.

**Comment by marandaneto** [comment]
upgrading Gradle to 7.0 and the latest plugin version 0.15.1, it works, not sure if its a Gradle 6.8.3 issue.
closing it, thanks :)

**Comment by marandaneto** [comment]
today I've gotten the same error, with a different package, so upgrading to Gradle 7 does not work either, it's flakiness somewhere, but I really can't isolate the problem.

**Comment by marandaneto** [comment]
@gabrielittner good tip, thanks
