### ISSUE TITLE
Invalid MavenPublish Configuration. Unable to find variant to publish named release. Try setting the 'androidVariantToPublish' property in the mavenPublish extension object to something that matches the variant that ought to be published.

### ISSUE THREAD

**Issue by marandaneto** [vanniktech/gradle-maven-publish-plugin#241]
Gradle 7.0
Plugin 0.15.1
AGP 4.1.3

* What went wrong:
Invalid MavenPublish Configuration. Unable to find variant to publish named release. Try setting the 'androidVariantToPublish' property in the mavenPublish extension object to something that matches the variant that ought to be published.

This error is gotten when using the base plugin:

```
mavenPublishing {
    configure(com.vanniktech.maven.publish.AndroidLibrary(com.vanniktech.maven.publish.JavadocJar.Javadoc()))
}
```

the default variant is already `release` so I'd say it'd not be necessary nothing else other than the basic configuration in the base plugin right, `pom`, `signAllPublications` and `configure`

**Comment by gabrielittner** [comment]
I think this a bug on our side. Could you try wrapping the configure call into `afterEvaluate` to see if that helps?

**Comment by marandaneto** [comment]
@gabrielittner I will retry late this week

**Comment by ntoskrnl** [comment]
@marandaneto I had the same issue, using `aferevaluate` fixes this issue.

**Comment by marandaneto** [comment]
yep, for me too, forgot to reply, thanks

**Comment by gabrielittner** [comment]
Thanks for the update, we'll have a fix for this in the next release

**Comment by gigaga** [comment]
Hi @gabrielittner 

Same issue for me :( Can u tell me when the next release will be publish?

Regards,
