### ISSUE TITLE
Javadoc task breaks when using Gradle Toolchain functionality

### ISSUE THREAD

**Issue by benjamintboyle** [vanniktech/gradle-maven-publish-plugin#242]
Plugin breaks 'javadoc' task when using the [Gradle Toolchain functionality](https://docs.gradle.org/current/userguide/toolchains.html) introduced in Gradle 6.7.

If toolchain language is set to '8' in project build.gradle:
```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
```
But if the gradle wrapper is run with a local JDK11 distribution, the plugin tries to add the '-html5' option to the javadoc task. The task fails because the JDK8 javadoc tool does not know the 'html5' option.

**Comment by benjamintboyle** [comment]
The below run shows an example of the issue for the 'JDK 11' check:
https://github.com/ReactiveX/RxJava/pull/7239/checks

**Comment by gabrielittner** [comment]
We need to obtain the toolchain like this: `val toolchain = project.extensions.getByType<JavaPluginExtension>().toolchain` and use that for our check on whether to add these option instead if using `JavaVersion.current()`. Relevant code https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/kotlin/com/vanniktech/maven/publish/legacy/BaseSetup.kt#L136-L141

**Comment by benjamintboyle** [comment]
Will that work if the end user is not using the toolchain functionality?

**Comment by gabrielittner** [comment]
We can probably fall back to the current behavior if it's not set. I'll try out what the behavior is when I implement the change

**Comment by gabrielittner** [comment]
This should now work correctly with 0.16.0 which is on it's way to maven central and should be available soon
