### ISSUE TITLE
How to publish to an internal repository?

### ISSUE THREAD

**Issue by Zhelyazko** [vanniktech/gradle-maven-publish-plugin#243]
I'm building an internal-use only library and want to publish it to our private Maven (Nexus) repository. But when I run:
```
./gradlew publish --no-daemon --no-parallel
```

I receive an error that maven username & password are not setup:
```
Credentials required for this build could not be resolved.
> The following Gradle properties are missing for 'mavenCentral' credentials:
    - mavenCentralUsername
    - mavenCentralPassword
```

I've configured a publication to our private repo as follows:
```
afterEvaluate {
    publishing {
        repositories {
            maven {
                name = "Private repo"
                val releasesRepoUrl = uri("https://****/repository/maven-releases/")
                val snapshotsRepoUrl = uri("https://****/repository/maven-snapshots/")

                url = if (version.toString().endsWith("SNAPSHOT")) {
                    snapshotsRepoUrl
                } else {
                    releasesRepoUrl
                }

                credentials {
                    username = System.getenv("INTERNAL_REPO_USERNAME")
                    password = System.getenv("INTERNAL_REPO_PASSWORD")
                }
            }
        }
    }
}
```

How can I disable the publishing to Maven Central or can I configure a gradle task to upload only to our private repo?

P.S. Publishing to the Maven Local (`./gradlew publishToMavenLocal`) works fine, so the rest of my setup should be ok.

**Comment by gabrielittner** [comment]
`publish` will publish to all configured repositories. To publish to a specific one you can use `publishAllPublicationsTo[RepoName]Repository` so in your example case it should be `publishAllPublicationsToPrivateRepoRepository`.

Once #244 is through we would also have a way of disabling the default repository.
