### ISSUE TITLE
mavenPublish not found

### ISSUE THREAD

**Issue by TheOnlyTails** [vanniktech/gradle-maven-publish-plugin#255]
I tried to change the default Sonatype host using this code snippet (in my `build.gradle.kts`):
```kt
allprojects {
    plugins.withId("com.vanniktech.maven.publish") {
        mavenPublish {
            sonatypeHost = SonatypeHost.S01
        }
    }
}
```
However, both `mavenPublish` and `sonatypeHost` cannot be found.

**Comment by rnett** [comment]
For `.kts`, instead of `plugins.withId` you generally want to get the equivalent extension, which is the receiver of the `mavenPublish`.  So something like:
```kotlin
extensions.getByType<com.vanniktech.maven.publish.MavenPublishPluginExtension>().apply {
    sonatypeHost = SonatypeHost.S01
}
```

**Comment by TheOnlyTails** [comment]
I believe it worked, but now I have a bigger problem: https://gist.github.com/TheOnlyTails/8a1383d455e30528032bf52130ea89bd

How exactly do I need to format my private key in `gradle.properties`?

**Comment by rnett** [comment]
You're using `signingInMemoryKey`?  I had no issue using the environment variable(`ORG_GRADLE_PROJECT_signingInMemoryKey`, set from GitHub secrets) with `gpg --armor --export-secret-key`.  I did have an issue for a while because `gpg --armor --export` exports the public key.

**Comment by TheOnlyTails** [comment]
I am using in-memory keys, but if I just copy it into the secret, it doesn't work. I don't know if I need to remove newlines, escape them, or something else.

**Comment by twyatt** [comment]
> I don't know if I need to remove newlines, escape them, or something else.

@TheOnlyTails I followed the process described in https://github.com/vanniktech/gradle-maven-publish-plugin/pull/201#discussion_r584270633 and it worked for me.

**Comment by TheOnlyTails** [comment]
@twyatt I tried it, and now I'm getting a fun
```
Caused by: org.bouncycastle.openpgp.PGPException: checksum mismatch at 0 of 20
```

**Comment by twyatt** [comment]
@TheOnlyTails I believe that means you have the wrong key password. Are you using `signingInMemoryKeyPassword` property (note the `Key` between `Memory` and `Password`)?

**Comment by TheOnlyTails** [comment]
I see here that I need to use `signingInMemoryPassword`; Plus, using `signingInMemoryKeyPassword` doesn't work either.

![image](https://user-images.githubusercontent.com/65342367/121061650-cb1f1600-c7cc-11eb-8a16-439d47905579.png)

**Comment by TheOnlyTails** [comment]
Welp - I had 2 Ss.

**Comment by TheOnlyTails** [comment]
IT'S WORKING! 

It may have taken me 3 months, but it's finally working.

**Comment by TheOnlyTails** [comment]
@twyatt well, not exactly. For some reason, after the workflow finishes successfully, the Nexus dashboard still shows the staging repo as Closed with `Event: 1 rule failed: Default Always Run`.

**Comment by twyatt** [comment]
Unfortunately I haven't attempted pushing artifacts to Maven Central, signed with the in-memory key, yet. Should be able to give it a try in the coming week or two though.

**Comment by TheOnlyTails** [comment]
Hmm, ok then. I'll reopen the issue if anyone can help.

**Comment by gabrielittner** [comment]
@TheOnlyTails Could you share a screenshot of what you see on the website?

**Comment by TheOnlyTails** [comment]
Here it is:


![image](https://user-images.githubusercontent.com/65342367/121077040-ca43af80-c7df-11eb-9965-9b780250b3fb.png)
![image](https://user-images.githubusercontent.com/65342367/121077050-cd3ea000-c7df-11eb-927d-d7660dcd2cae.png)

**Comment by TheOnlyTails** [comment]
Oops, accidentally closed.

**Comment by gabrielittner** [comment]
It seems like the release you a trying to publish has already been published https://repo.maven.apache.org/maven2/com/theonlytails/loottables/0.2.11/ That would explain the "does not allow updating" part of the failure messages

**Comment by TheOnlyTails** [comment]
so - for some reason I forgot to merge my 2 version properties, so I only updated the old one

**Comment by TheOnlyTails** [comment]
It works. Thank you so much. These has been a long few months. 🎉
