### ISSUE TITLE
Error: Task publishAllPublicationsToMavenCentralRepository not found after upgrading 0.14.2 -> 0.15.1 for gradle plugin

### ISSUE THREAD

**Issue by rnett** [vanniktech/gradle-maven-publish-plugin#256]
I upgraded from `0.14.2` to `0.15.1`, and am now seeing the error [here](https://gist.github.com/rnett/d646b3caf7a66524465118d3be07f068).

As the name implies, this project is a gradle plugin; the error does not happen on my other Kotlin/JVM module.  I'm using the plugin publish plugin version `0.14.0`.

**Comment by rnett** [comment]
The configuration files are [here (parent)](https://github.com/rnett/krosstalk/blob/main/build.gradle.kts) and [here (module)](https://github.com/rnett/krosstalk/blob/main/build.gradle.kts#L37), although note that it's currently disabled from applying to the gradle plugin project.

**Comment by rnett** [comment]
It also works just fine if I disable `id("com.gradle.plugin-publish")`, which is what I'm doing as a workaround.

**Comment by Mygod** [comment]
Can reproduce this too.

**Comment by gabrielittner** [comment]
This seems to be happening when something causes the task to be configured eagerly. I will take a look to possibly avoid this on our side but it should also be avoidable by removing whatever causes eager task configuration

**Comment by gabrielittner** [comment]
This will be resolved in the next release

**Comment by Mygod** [comment]
Still present in 0.16.0.

**Comment by gabrielittner** [comment]
@Mygod Released 0.17.0 where uploadArchives got removed yesterday. Please try out that release
