### ISSUE TITLE
Signing fails w/ Could not read PGP secret key for in memory key, on SNAPSHOT build

### ISSUE THREAD

**Issue by rnett** [vanniktech/gradle-maven-publish-plugin#257]
I'm getting build failures because of signing for a snapshot build.  I was under the impression that signing was disabled for snapshot versions by default.

The error:
```
> Task :compiler:krosstalk-compiler-plugin:signMavenPublication FAILED

13 actionable tasks: 6 executed, 7 up-to-date
* What went wrong:
Could not evaluate onlyIf predicate for task ':compiler:krosstalk-compiler-plugin:signMavenPublication'.
> Could not read PGP secret key
```

The key is properly configured (or so I thought), so I'm not sure why this is happening, even on a snapshot build.  I'm setting `ORG_GRADLE_PROJECT_signingInMemoryKey` and only that, since the key has no passpharse.

**Comment by rnett** [comment]
So the error was because I was exporting the public key 🤦.  Still not sure why it's happening for snapshots though.

**Comment by anggrayudi** [comment]
Have you tried to wrap it with double quotes? For example, `"Ob2280tEpr64iB9b6YRkWil"`

**Comment by gabrielittner** [comment]
Snapshot builds will use signing if it's set up, we don't differentiate there. The only difference is that a snapshot build will not fail if signing is not configured at all.
