### ISSUE TITLE
androidJavaDocs task error in china

### ISSUE THREAD

**Issue by panpf** [vanniktech/gradle-maven-publish-plugin#258]
Because the androidJavaDocs task requires access to `https://developer.android.com/reference`, and China has blocked `android.com`, it often fails when used in China

If the `https://developer.android.com/reference` link is not necessary, can I provide a configuration option to disable it?

**Comment by ag2s20150909** [comment]
Replace to https://developer.android.google.cn/reference

**Comment by gabrielittner** [comment]
With the next release we will not use the `androidJavaDocs` task anymore and javadocs will be generated by AGP.
