### ISSUE TITLE
How to exclude sources.jar on 0.15.x?

### ISSUE THREAD

**Issue by ntoskrnl** [vanniktech/gradle-maven-publish-plugin#260]
I am testing publication with the latest version of the plugin, but I cannot exclude sources.

I have the following config:
```groovy
mavenPublishing {
   // some pom config ...
   afterEvaluate {
      configure(new AndroidLibrary(new JavadocJar.None(), false))
  }
}
```

When I test publishing with local maven repository `./gradlew publishToMavenLocal`, I still see sources jar.
Is this normal?

**Comment by gabrielittner** [comment]
Hi, yes this is normal, the jar is empty when you pass in `false`.

**Comment by ntoskrnl** [comment]
oh, ok! good to know :)
