### ISSUE TITLE
Nexus package to a separate artifact? 

### ISSUE THREAD

**Issue by yogurtearl** [vanniktech/gradle-maven-publish-plugin#265]
Would you consider publishing everything in the nexus package as a separate artifact(s)? 

https://github.com/vanniktech/gradle-maven-publish-plugin/tree/master/src/main/kotlin/com/vanniktech/maven/publish/nexus

maybe `com.vannitech:nexus-staging-api` and `com.vannitech:gradle-nexus-close-release-task`? 

This would allow just pulling in the retrofit service and/or task.

**Comment by martinbonnin** [comment]
+1 for that. Extracting the Nexus Client shouldn't be too complex. I think the most complex part would be transforming  the project in a multi-module build and handling the publishing, etc... Maybe move the scripts to `build.gradle.kts` ? I could look into that if we feel that's a route we want to take.

**Comment by gabrielittner** [comment]
No objections against this from my side. Do you want to open a PR?

**Comment by martinbonnin** [comment]
👍  Will look into this. It might be several PRs, the first one certainly moving the build scripts to Kotlin.
