### ISSUE TITLE
Execution optimizations have been disabled for task ':sentry-android-core:androidJavadocJar' to ensure correctness due to the following reasons

### ISSUE THREAD

**Issue by marandaneto** [vanniktech/gradle-maven-publish-plugin#267]
Hi, thanks for the plugin.

using the latest Gradle 7, there are a few warnings being triggered by Gradle and/or AGP (4.2.x currently)

> Task :sentry-android-core:distTar
Execution optimizations have been disabled for task ':sentry-android-core:distTar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/marandaneto/Github/sentry-java/sentry-android-core/build/outputs/aar'. Reason: Task ':sentry-android-core:distTar' uses this output of task ':sentry-android-core:bundleDebugAar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :sentry-android-core:androidJavadocJar
Execution optimizations have been disabled for task ':sentry-android-core:androidJavadocJar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/marandaneto/Github/sentry-java/sentry-android-core/build/libs/sentry-android-core-5.0.2-SNAPSHOT-javadoc.jar'. Reason: Task ':sentry-android-core:distTar' uses this output of task ':sentry-android-core:androidJavadocJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :sentry-android-core:androidSourcesJar
Execution optimizations have been disabled for task ':sentry-android-core:androidSourcesJar' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/marandaneto/Github/sentry-java/sentry-android-core/build/libs/sentry-android-core-5.0.2-SNAPSHOT-sources.jar'. Reason: Task ':sentry-android-core:distTar' uses this output of task ':sentry-android-core:androidSourcesJar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :sentry-android-core:generatePomFileForMavenPublication
Execution optimizations have been disabled for task ':sentry-android-core:generatePomFileForMavenPublication' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/marandaneto/Github/sentry-java/sentry-android-core/build/publications/maven/pom-default.xml'. Reason: Task ':sentry-android-core:distTar' uses this output of task ':sentry-android-core:generatePomFileForMavenPublication' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#implicit_dependency for more details about this problem.

How to reproduce:
https://github.com/getsentry/sentry-java
`make dryRelease`

I'm not entirely sure it's the Plugin's fault but worth checking, thanks.

**Comment by gabrielittner** [comment]
In all messages the explanation is 
> Reason: Task ':sentry-android-core:distTar' uses this output of task '...' without declaring an explicit or implicit dependency. 

So the issue seems to be with `distTar` which does not come from this plugin

**Comment by eygraber** [comment]
It's happening in my build as well, but mentions the publishing tasks - https://github.com/eygraber/compose-color-picker/runs/2910880808
