### ISSUE TITLE
Document how to disable maven central

### ISSUE THREAD

**Issue by vRallev** [vanniktech/gradle-maven-publish-plugin#269]
I've seen #244 and tried:
```groovy
apply plugin: 'com.vanniktech.maven.publish'

mavenPublish {
  sonatypeHost = null
}
```
But I receive the following error:
```
* What went wrong:
A problem occurred evaluating script.
> Parameter specified as non-null is null: method com.vanniktech.maven.publish.MavenPublishPluginExtension.setSonatypeHost, parameter <set-?>
```
How can I disable the publishing to maven central?

**Comment by gabrielittner** [comment]
The chage from that pr hasn't be released yet. There are 2 or 3 smaller things that I want to fix before cutting a release, hopefully soon.

Currently you can't disable it but if you add oner repository to publish to you can use `publishAllPublicationsTo<name-of-repo>Repository` to only publish to the one you have created in the mean time

**Comment by vRallev** [comment]
Yes, that's what I'm doing for now. But it's dangerous to leave the other tasks for Maven Central in place. Thanks for the explanation.

**Comment by gabrielittner** [comment]
0.16.0 with this is on it's way to maven central and should be available soon
