### ISSUE TITLE
0.15.1 -> 0.16.0 upgrade fails with missing mavenPublish overload

### ISSUE THREAD

**Issue by akarnokd** [vanniktech/gradle-maven-publish-plugin#275]
Hi. After upgrading to 0.16.0, the snapshot process in RxJava fails:

```
Build file '/home/runner/work/RxJava/RxJava/build.gradle' line: 186

* What went wrong:
A problem occurred evaluating root project 'rxjava'.
> No signature of method: build_9zbds036kkmpaw44gv9edrtry.mavenPublish() is applicable for argument types:
 (build_9zbds036kkmpaw44gv9edrtry$_run_closure17) values: [build_9zbds036kkmpaw44gv9edrtry$_run_closure17@5998fa25]
```

[build.gradle line 186](https://github.com/ReactiveX/RxJava/blob/3.x/build.gradle#L186-L190)

Please advise.

**Comment by gabrielittner** [comment]
`nexus {}` was removed together with `nexusOptions`. I will update the changelog to also explicitly mention that method. You don't need to set `stagingProfile` anymore we handle this internally now.
