### ISSUE TITLE
Feature request: Gradle task `publishSnapshot`

### ISSUE THREAD

**Issue by anggrayudi** [vanniktech/gradle-maven-publish-plugin#278]
Suppose that I have this `gradle.properties`:
```
GROUP=com.test.mylibrary
POM_ARTIFACT_ID=mylibrary
VERSION_NAME=3.0.5
```
So when I execute the following Gradle tasks without having to change `VERSION_NAME`:
* `publish` will upload `3.0.5`
* `publishSnapshot` will upload `3.0.5-SNAPSHOT`

These tasks ease us in publishing snapshots manually, so I no longer need to append suffix `-SNAPSHOT` to `VERSION_NAME` in `gradle.properties` each time I want to publish snapshots. Switching to snapshot or stable version will be simpler.

I've tried this command, but did not work:
```
./gradlew publish -PVERSION_NAME=3.0.5-SNAPSHOT
```

I've requested this feature here #153, but the issue was closed for no reason. I wish you will not close this issue again.

**Comment by gabrielittner** [comment]
Afaik the version of a project can not be computed by a task so we would rely on the task being requested to change configuration which is not great for things like configuration caching. Gradle relies on the version to also built the pom directly. If you want this feature please open a feature request with Gradle to ask them to support in directly in the `maven-publish` plugin.

In regards to `./gradlew publish -PVERSION_NAME=3.0.5-SNAPSHOT` not working, please open a bug with a reproducer, I've just tested it again and don't have any issues with it.
