### ISSUE TITLE
[Question] How to set artifactId for individual modules

### ISSUE THREAD

**Issue by ntoskrnl** [vanniktech/gradle-maven-publish-plugin#280]
We set up a base-plugin in our project, and the library has several modules. Pom config is set up via gradle DSL (i.e. using `pom { }`) as described in README.

When I publish, the plugin uses gradle module name as `artifactId` and I would like to change it. How do I set up `artifactId` for each module individually?

I tried adding `POM_ARTIFACT_ID = ...` or `pom.artificatId = ...` inside `mavenPublishing { }` block of the module, but it didn't work.

**Comment by ntoskrnl** [comment]
I found a solution. For android publications the plugin's `configure()` method creates a publication named "maven". We can find it by name and change `artifactId`. But I just applied name to all publications (there will only be one per Gradle module anyway).

 I added this to the module:
```groovy
publishing {
    publications.all { p ->
        p.artifactId = "newname"
    }
}
```

**Comment by RBusarow** [comment]
Thank you, @ntoskrnl, for posting your solution!  This needs to be translated a little bit in order to work for the Kotlin DSL.

In Kotlin, `publications` gives us a collection of `Publication`, which doesn't have the `artifactId` property.  We need to cast that `p: Publication` to a `MavenPublication`.

```kotlin
publishing {
  publications
    .filterIsInstance<MavenPublication>()
    .forEach { p ->
      p.artifactId = "my-artifact-id"
    }
}
```
