### ISSUE TITLE
[Feature request] An option that read maven central passord from local.properties

### ISSUE THREAD

**Issue by ichenhe** [vanniktech/gradle-maven-publish-plugin#281]
I know it is recommended to set them in ~/.gradle/gradle.properties.

But if I have more than one maven central account, things get troublesome. So I prefer put them in `local.properties` to the main properties file.

**Comment by Favorlock** [comment]
I'd like to second this request. I was doing the exact same thing before with an older version of the plugin and I have yet to figure out how to do this with the latest version. Would be great if a way to programmatically set the username/password was possible.

**Comment by Favorlock** [comment]
After some digging I finally figured out how this can be done.

```groovy
ext.local = new Properties()
File file = project.rootProject.file('local.properties')
if (file.exists()) local.load(file.newDataInputStream())
    
publishing {
    repositories {
        maven {
            def releaseRepoUrl = 'https://oss.sonatype.org/service/local/staging/deploy/maven2/'
            def snapshotRepoUrl = 'https://oss.sonatype.org/content/repositories/snapshots/'
            url = version.endsWith('SNAPSHOT') ? snapshotRepoUrl : releaseRepoUrl
            credentials {
                username = local.getProperty('deployment.username')
                password = local.getProperty('deployment.password')
            }
        }
    }
}
```

**Comment by gabrielittner** [comment]
I think it would be best to open a feature request with Gradle for this. We are just using their credentials API, so it would need to be something that needs to be supported on their side.

**Comment by martinbonnin** [comment]
@ichenhe @Favorlock FWIW, you can also use environment variables to specify the password and username:

```
export ORG_GRADLE_PROJECT_mavenCentralUsername=$username
export ORG_GRADLE_PROJECT_mavenCentralPassword=$password
```

If you put this in a file `personnal_credential.sh` (and other credentials in e.g. `company_credential.sh`, you can source the appropriate file before releasing. Also CI usually use environment variables so this setup si closer to something you can use on Github Actions for an example.

**Comment by ichenhe** [comment]
@martinbonnin Thanks. But, environment variables seem to be more suitable for CI. It is not applicable in ordinary development.

Of course, publishing to maven is not a very frequent operation, so thank you for your tip.
