### ISSUE TITLE
Artefact and repository not published

### ISSUE THREAD

**Issue by alexandre-thauvin** [vanniktech/gradle-maven-publish-plugin#282]
First, thanks for the amazing work guys.
I discovered that my artefacts were not published with the command  

./gradlew publish --no-daemon --no-parallel

I get a Build Successful but no repository are published in the Nexus Repository Manager (empty). I tried without the plugin with a manual script in build.gradle and it is published correctly but I have a [Signature validation failure](https://stackoverflow.com/questions/68447837/gradle-signing-android-publications-cannot-perform-signing-task-because-it-has), that's why I'm trying to publish with this plugin.

Here is my root build.gradle:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.5.21'
    repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.vanniktech:gradle-maven-publish-plugin:0.17.0' // NEW
        classpath 'org.jetbrains.dokka:dokka-gradle-plugin:1.4.10.2' // NEW
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    plugins.withId("com.vanniktech.maven.publish") {
        mavenPublish {
            releaseSigningEnabled = true
            sonatypeHost = "S01"
        }
    }
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

apply plugin: "com.vanniktech.maven.publish"
```

Here is my gradle.properties lib lvl:
```
# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app's APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

GROUP=io.github.WeLoopTeam
POM_ARTIFACT_ID=weloop
VERSION_NAME=1.1.5

POM_NAME=weloop
POM_PACKAGING=aar

POM_DESCRIPTION=weloop android sdk
POM_INCEPTION_YEAR=2020

POM_URL=https://github.com/WeLoopTeam/WeLoop-Android
POM_SCM_URL=https://github.com/WeLoopTeam/WeLoop-Android
POM_SCM_CONNECTION=scm:git@github.com:WeLoopTeam/WeLoop-Android.git.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:WeLoopTeam/WeLoop-Android.git.git

POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT

signing.keyId=xxx
signing.password=xxx
signing.secretKeyRingFile=xxx
ossrhUsername=xxx
ossrhPassword=xxx
```

If you need more logs let me know and I will run with --debug or --info

When I try to publish via the plugin and ask the Sonatype team why no repository and artefacts are found in my Nexus repository

![image](https://user-images.githubusercontent.com/27420929/126399181-3d70f429-92e1-4065-acba-7704ac4bb965.png)

**Comment by alexandre-thauvin** [comment]
![image](https://user-images.githubusercontent.com/27420929/126399181-3d70f429-92e1-4065-acba-7704ac4bb965.png)

When I try to publish via the plugin

**Comment by Shashank02051997** [comment]
@alexandre-thauvin i am facing the same issue

**Comment by gabrielittner** [comment]
Can you share the build log (without debug/info)?


```

ossrhUsername=xxx
ossrhPassword=xxx
```
Thesse should be `mavenCentralUsername` and `mavenCentralPassword`

https://github.com/vanniktech/gradle-maven-publish-plugin#where-to-upload-to

**Comment by Shashank02051997** [comment]
@gabrielittner my issue is resolved... thanks for the lib

**Comment by alexandre-thauvin** [comment]
How did you solved the issue ? @Shashank02051997 
I also tried with `mavenCentralUsername` and `mavenCentralPassword` it didn't work. However I gave up on the lib and I succeeded with a manual script; https://stackoverflow.com/questions/68447837/gradle-signing-android-library-publications-cannot-perform-signing-task-because/68505768#68505768

**Comment by Shashank02051997** [comment]
@alexandre-thauvin after adding the below code

allprojects {
    plugins.withId("com.vanniktech.maven.publish") {
        mavenPublish {
            sonatypeHost = "S01"
        }
    }
}

and apply plugin: 'com.vanniktech.maven.publish' this plugin at the bottom of the code which resolved my issue
