### ISSUE TITLE
Build Fail Regular Sign - Windows

### ISSUE THREAD

**Issue by Nageshks** [vanniktech/gradle-maven-publish-plugin#285]
### intermixing of path no matter what is signing.secretKeyRingFile
**Error**
`Unable to retrieve secret key from key ring file 'C:\Users\Developer\AndroidStudioProjects\MaterialSheetExample\materialsheetlib\"C:UsersDeveloper.gradlesecring.gpg"' as it does not exist`

root/local.properties
``` groovy
sdk.dir=C\:\\Users\\Developer\\AppData\\Local\\Android\\Sdk
signing.keyId=****4306
signing.password=*********
signing.secretKeyRingFile=C\:\\Users\\Developer\\secring.gpg
```

**Comment by gabrielittner** [comment]
Signing is done with the Gradle `signing` plugin https://docs.gradle.org/current/userguide/signing_plugin.html Please check with Gradle what the issue is
