### ISSUE TITLE
Remove check for old credential vars

### ISSUE THREAD

**Issue by JakeWharton** [vanniktech/gradle-maven-publish-plugin#287]
I'm stuck on 0.14.x for our projects because newer versions fail the build if the old env vars are present. This is very user-hostile behavior. I have the new and old credential vars in my `~/.gradle/gradle.properties` and I do not want to remove them as older projects still use them. This means I cannot upgrade any project past 0.14.x without first upgrading every project (I probably interact with ~40).

A few minor versions seems like enough for people to have migrated so I propose removing the check completely for the next one.

As an aside: The old names were more accurate as the credentials are specifically to Sonatype and not to Maven Central itself.

**Comment by vanniktech** [comment]
I'm having the same problem. How about removing that check and instead printing out a warning?

> As an aside: The old names were more accurate as the credentials are specifically to Sonatype and not to Maven Central itself.

Agreed.

**Comment by gabrielittner** [comment]
I think we can just remove them now, it's been quite some time since we stopped using them

**Comment by gabrielittner** [comment]
In regards to naming: I named the repository to publish to `mavenCentral` even if it's technically not correct because many don't understand how the exactly everything and this way the task to run is `publish...ToMavenCentralRepository` which is the goal, even if it goes through Sonatype. Since we're using Gradle's credential API the property names are derived from that.

**Comment by JakeWharton** [comment]
Yep, that makes sense. It matches the mental model that users have.

**Comment by gabrielittner** [comment]
Checks will be removed in the next release

**Comment by JakeWharton** [comment]
Hello. Going full blown user here...

Do you all have rough estimate of when a new release might be out or if anything is blocking it?

**Comment by gabrielittner** [comment]
I want to do a few smaller things tomorrow (main part is the bug that Jesse filed) and then will do a release
