### ISSUE TITLE
Signing required not working as intended

### ISSUE THREAD

**Issue by gabrielittner** [vanniktech/gradle-maven-publish-plugin#29]
When the plugin is only applied to modules the task graph will never contain `uploadArchives`, instead it will have `:<modulename>:uploadArchives`.

```
afterEvaluate
    signing {
        required {
            println("version ${!project.version.contains("SNAPSHOT")}")
            println("task ${project.gradle.taskGraph.hasTask("uploadArchives")}")
            !project.version.contains("SNAPSHOT") && project.gradle.taskGraph.hasTask("uploadArchives")
        }
    }
}
```

Slightly related: We should move the configuration of signing out of afterEvaluate in the plugin, required is already evaluated lazily and `sign project.configurations.archives` doesn't have to wait for anything. This would make it easier to override the plugin behavior in build scripts.

**Comment by vanniktech** [comment]
Yup like we talked about this offline we should fix it.
