### ISSUE TITLE
How to set GROUP and VERSION using the base plugin

### ISSUE THREAD

**Issue by bmarty** [vanniktech/gradle-maven-publish-plugin#304]
Hello,

I'm trying to use [the base plugin](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/README.md#base-plugin), because I want to publish and Android library to MavenCentral without source code and without Javadoc.

Version is `com.vanniktech:gradle-maven-publish-plugin:0.18.0`

Here is my configuration:

### Main build.gradle file

```groovy
allprojects {
    plugins.withId("com.vanniktech.maven.publish.base") {
        GROUP = "my.group"
        VERSION = "1.0.0"

        mavenPublishing {
            publishToMavenCentral("S01")
            pomFromGradleProperties()
            signAllPublications()
        }
    }
}
```

### Project build.gradle file

```groovy
import com.vanniktech.maven.publish.AndroidLibrary
import com.vanniktech.maven.publish.JavadocJar

apply plugin: "com.vanniktech.maven.publish.base"

mavenPublishing {
    configure(new AndroidLibrary(new JavadocJar.Empty(), false))
}
```

### Result

I get this error: 
> groovy.lang.MissingPropertyException: Could not set unknown property 'VERSION'

If GROUP and VERSION are not set (if I comment out the 2 lines), when publishing using this command:

```bash
./gradlew publish --no-daemon --no-parallel
```

I get this error:

```bash
Could not PUT 'https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/android/project/unspecified/project-unspecified.aar'. Received status code 400 from server: Bad Request
```

it seems that group and version (= "unspecified") are not correct in this path.

Using the main plugin, it works fine, but Javadoc and source code are also published, and I cannot find a way to disable this using the main plugin.

Thanks!

**Comment by gabrielittner** [comment]
Could you try

```
allprojects {
    plugins.withId("com.vanniktech.maven.publish.base") {
        group = "my.group"
        version = "1.0.0"

//...
````

**Comment by Ahmad-Hamwi** [comment]
@gabrielittner setting the variables to lowercase did it for me, thank you.
The documentation should probably be edited so it matches the lower case variables.

**Comment by vanniktech** [comment]
@Ahmad-Hamwi mind creating a PR to fix the documentation?

**Comment by Ahmad-Hamwi** [comment]
@vanniktech Sure, the pull request is now created.

**Comment by bmarty** [comment]
Thanks, sorry, I was not able to test this earlier, but it's working great!
Thanks @Ahmad-Hamwi for the PR :)
