### ISSUE TITLE
SNAPSHOT builds not publishing with correct suffix 

### ISSUE THREAD

**Issue by kevincianfarini** [vanniktech/gradle-maven-publish-plugin#310]
I'm using gradle-maven-publish-plugin 0.18.0 with my company's internal artifactory repo to publish a multiplatform kotlin project. Some configuration was required to get this working. 

```kotlin
  plugins.withType<com.vanniktech.maven.publish.MavenPublishPlugin> {
    val mavenPublish =
      project.extensions["mavenPublish"] as com.vanniktech.maven.publish.MavenPublishPluginExtension
    mavenPublish.sonatypeHost = null

    val publishing = project.extensions["publishing"] as PublishingExtension
    publishing.repositories {
      maven {
        name = "Artifactory"
        credentials {
          username = System.getenv("SONATYPE_NEXUS_USERNAME")
          password = System.getenv("SONATYPE_NEXUS_PASSWORD")
        }
        url = uri("https://myartifactory/artifactory/releases")
      }
    }
  }
```

This configuration allows me to `publishToMavenLocal` perfectly fine, and results in the following tree. For context, the `yoga` module below lives as a git submodule where JNI bindings and cinterop are manually created as part of my gradle build. 

```
.
└── kriya
    ├── kriya
    │   ├── 0.0.8-SNAPSHOT
    │   │   ├── kriya-0.0.8-SNAPSHOT-javadoc.jar
    │   │   ├── kriya-0.0.8-SNAPSHOT-kotlin-tooling-metadata.json
    │   │   ├── kriya-0.0.8-SNAPSHOT-sources.jar
    │   │   ├── kriya-0.0.8-SNAPSHOT.jar
    │   │   ├── kriya-0.0.8-SNAPSHOT.module
    │   │   ├── kriya-0.0.8-SNAPSHOT.pom
    │   │   └── maven-metadata-local.xml
    │   └── maven-metadata-local.xml
    ├── kriya-jvm
    │   ├── 0.0.8-SNAPSHOT
    │   │   ├── kriya-jvm-0.0.8-SNAPSHOT-javadoc.jar
    │   │   ├── kriya-jvm-0.0.8-SNAPSHOT-sources.jar
    │   │   ├── kriya-jvm-0.0.8-SNAPSHOT.jar
    │   │   ├── kriya-jvm-0.0.8-SNAPSHOT.module
    │   │   ├── kriya-jvm-0.0.8-SNAPSHOT.pom
    │   │   └── maven-metadata-local.xml
    │   └── maven-metadata-local.xml
    ├── kriya-macosx64
    │   ├── 0.0.8-SNAPSHOT
    │   │   ├── kriya-macosx64-0.0.8-SNAPSHOT-cinterop-yoga.klib
    │   │   ├── kriya-macosx64-0.0.8-SNAPSHOT-javadoc.jar
    │   │   ├── kriya-macosx64-0.0.8-SNAPSHOT-metadata.jar
    │   │   ├── kriya-macosx64-0.0.8-SNAPSHOT-sources.jar
    │   │   ├── kriya-macosx64-0.0.8-SNAPSHOT.klib
    │   │   ├── kriya-macosx64-0.0.8-SNAPSHOT.module
    │   │   ├── kriya-macosx64-0.0.8-SNAPSHOT.pom
    │   │   └── maven-metadata-local.xml
    │   └── maven-metadata-local.xml
    └── yoga
        ├── 0.0.8-SNAPSHOT
        │   ├── maven-metadata-local.xml
        │   ├── yoga-0.0.8-SNAPSHOT-javadoc.jar
        │   ├── yoga-0.0.8-SNAPSHOT-sources.jar
        │   ├── yoga-0.0.8-SNAPSHOT.jar
        │   ├── yoga-0.0.8-SNAPSHOT.module
        │   └── yoga-0.0.8-SNAPSHOT.pom
        └── maven-metadata-local.xml
```

When I try to publish this same build to artifactory using the generated `./gradlew publishAllPublicationsToArtifactoryRepository` I get the following error. 

```
* What went wrong:
Execution failed for task ':core:publishJvmPublicationToArtifactoryRepository'.
> Failed to publish publication 'jvm' to repository 'Artifactory'
   > Could not PUT 'https://myartifactory/artifactory/releases/com/mycompany/kriya/kriya-jvm/0.0.8-SNAPSHOT/kriya-jvm-0.0.8-20211004.144016-1.jar'. Received status code 409 from server: Conflict
```

I've seen this error traditionally happen when trying to overwrite a publication that already exists with the same version. This is not the case here. If I increment the version number and try to publish, it fails with the same error. I have a suspicion it has something to do with the name of the jarfile it's publishing --`0.0.8-SNAPSHOT/kriya-jvm-0.0.8-20211004.144016-1.jar`. 

In contrast with `publishToMavenLocal`, this jarfile does not include the `-SNAPSHOT` suffix, and I think that artifactory might be rejecting for that reason. This issue is also present if I only try to publish the JVM portions of the library with `gradlew publishJvmPublicationToArtifactoryRepository`. 

Any help is appreciated. I'm unsure if I'm doing something wrong or if this is an issue with the plugin.

**Comment by gabrielittner** [comment]
It is expected that `SNAPSHOT` is replaces with at timestamp. This is done so that you can publish the same snapshot multiple times without overwriting the file. When depending on a snapshot Gradle will be able to find these versions with a timestamp. The issue here is that apparently the timestamp was not updated correctly. I'd recommend trying a clean build, if that doesn't help please file an issue with Gradle as that logic is part of their code
https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/MavenLocalPublisher.java#L71-L73
