### ISSUE TITLE
Update Github repository description? 

### ISSUE THREAD

**Issue by martinbonnin** [vanniktech/gradle-maven-publish-plugin#311]
The description of the repo as of today reads:

```
Gradle plugin that configures an uploadArchives task to automatically upload all of your Java, 
Kotlin or Android libraries to any Maven instance.
```

Might be worth updating, especially since I'm not sure `uploadArchives` is still a thing? 

Quick proposal, feel free to edit/replace with something more appropriate:

```
A Gradle plugin that publishes your Android and Kotlin libraries, including sources and javadoc, 
to Maven Central or any other Nexus instance.
```

**Comment by jaredsburrows** [comment]
@gabrielittner @vanniktech I believe the README.md is fine but the "github description" can only be changed by the repo owner.

**Comment by vanniktech** [comment]
Thanks!

<img width="339" alt="Screen Shot 2022-05-28 at 09 30 47" src="https://user-images.githubusercontent.com/5759366/170815512-bec2c97a-99c7-4433-8ff0-055cf93de147.png">
