### ISSUE TITLE
Publish Only AAR

### ISSUE THREAD

**Issue by dineshkandan** [vanniktech/gradle-maven-publish-plugin#319]
How to publish only aar file not source to maven

**Comment by yizems** [comment]
![image](https://user-images.githubusercontent.com/16949474/147622644-baf84b78-5801-4fec-93fb-f3dd43af19b5.png)

**build.gradle**
```
configurations.maybeCreate("default")
artifacts.add("default", file('xxx.aar'))
apply plugin: "com.vanniktech.maven.publish"

publishing{
    publications{
        maven(MavenPublication) {
            artifact 'xxx.aar' 
        }
    }
}
```

**Comment by dineshkandan** [comment]
getting error 
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'clean' as a task with that name already exists.

another error
org.gradle.api.InvalidUserDataException: Cannot add a Publication with name 'maven' as a Publication with that name already exists.

**Comment by yizems** [comment]
看下这个版本是多少, 小于7.0么, 
![image](https://user-images.githubusercontent.com/16949474/147629178-3635f5b5-1c76-4e76-a7a6-48dcc8a2de27.png)
另外尝试换下 
```
publishing{
    publications{
       // maven 换成 别的, 随便一个值, 例如  myMaven
        maven(MavenPublication) {
            artifact 'xxx.aar' 
        }
    }
}
```

**Comment by gabrielittner** [comment]
Take a look at the base plugin https://github.com/vanniktech/gradle-maven-publish-plugin#base-plugin the `AndroidLibrary` object has parameters for javadoc and source jar.

**Comment by dineshkandan** [comment]
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'JavadocJar' for object of type org.gradle.api.publish.maven.internal.publication.DefaultMavenPublication.
