### ISSUE TITLE
A problem occurred evaluating project ':app'. > Failed to apply plugin [id 'com.vanniktech.maven.publish']  

### ISSUE THREAD

**Issue by himanshiThakur** [vanniktech/gradle-maven-publish-plugin#323]
gradle version :  classpath "com.android.tools.build:gradle:4.1.3"
Dependency version : com.vanniktech:gradle-maven-publish-plugin:0.13.0

ISSUE :
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.vanniktech.maven.publish']
   > Please define "GROUP" in your gradle.properties file

**Comment by vegaro** [comment]
Did you follow the "Setting properties" section of the README?
