### ISSUE TITLE
Task :compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by himanshiThakur** [vanniktech/gradle-maven-publish-plugin#324]
Task : compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':telscitame:compileReleaseJavaWithJavac'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x1df95051) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler)
 because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x1df95051

USING :
 classpath 'com.vanniktech:gradle-maven-publish-plugin:0.13.0'
 classpath "com.android.tools.build:gradle:4.1.3"

**Comment by gabrielittner** [comment]
This plugin in does not do any compilation, the task is from the Android Gradle plugin
