### ISSUE TITLE
Javadocs/sources are not published for test fixtures artifacts

### ISSUE THREAD

**Issue by ZacSweers** [vanniktech/gradle-maven-publish-plugin#325]
Repro repo for testing: https://github.com/slackhq/eithernet. 

There's a `testFixturesJavadoc` gradle task available, but it's not on the dependency path for publishing tasks

**Comment by gabrielittner** [comment]
We can probably apply this workaround ourselves until Gradle supports it https://github.com/gradle/gradle/issues/20539

**Comment by gabrielittner** [comment]
Fixed for the next release. Since test fixture sources are published in the same way as multi variant Android libraries it is likely that Android Studio won't be able to pick them up until https://issuetracker.google.com/issues/197636221 is resolved
