### ISSUE TITLE
Javadoc Not Generated in Kotlin Multiplatform Project

### ISSUE THREAD

**Issue by cedrickcooke** [vanniktech/gradle-maven-publish-plugin#333]
New to version `0.19.0`, publishing a Kotlin Multiplatform module that has both JVM and Android targets fails to generate a Javadoc jar for the JVM module.

The gradle publish still succeeds, but Sonatype won't let you close the repository to release it.

**Comment by gabrielittner** [comment]
Which version of AGP are you using?

**Comment by twyatt** [comment]
> Which version of AGP are you using?

7.1.2

**Comment by eygraber** [comment]
Is this caused by https://github.com/vanniktech/gradle-maven-publish-plugin/commit/a91b7655b99ddf3ac8e7f281b0f856fa3b3046bd#diff-f099650db8c1c47f7c5a8a1cbae50bad884723e41109ec858b0f0b9a04e15f8cR60

**Comment by vanniktech** [comment]
I've had the exact same issue here too: https://github.com/vanniktech/Emoji/

AGP: 7.0.4, Kotlin 1.6.21, Dokka 1.6.21 & Maven Publish 0.19.0
Ended up downgrading to Maven Publish 0.18.0 and it seems to be fixed.

This is also easily reproducible when cloning the project, bumping back to Maven Publish 0.19.0 and executing `./gradlew publishToMavenLocal` if you look at the `emoji-ios-jvm` directory there's no javadoc jar file.

**Comment by gabrielittner** [comment]
@eygraber It was caused by that commit but the linked line is intentional, when the Kotlin MPP and Android plugins are applied we only want to run `configure(KotlinMultiplatform(...))` which takes care of configuring publishing for all multiplatform targets.

**Comment by vanniktech** [comment]
Tried this out in https://github.com/vanniktech/Emoji/pull/838/files by doing a `./gradlew publishToMavenLocal` and it does look like everything is nicely generated:

```
➜  vanniktech git:(master) ✗ tree emoji-twitter*
emoji-twitter
├── 0.16.0-SNAPSHOT
│   ├── emoji-twitter-0.16.0-SNAPSHOT-javadoc.jar
│   ├── emoji-twitter-0.16.0-SNAPSHOT-javadoc.jar.asc
│   ├── emoji-twitter-0.16.0-SNAPSHOT-kotlin-tooling-metadata.json
│   ├── emoji-twitter-0.16.0-SNAPSHOT-kotlin-tooling-metadata.json.asc
│   ├── emoji-twitter-0.16.0-SNAPSHOT-sources.jar
│   ├── emoji-twitter-0.16.0-SNAPSHOT-sources.jar.asc
│   ├── emoji-twitter-0.16.0-SNAPSHOT.jar
│   ├── emoji-twitter-0.16.0-SNAPSHOT.jar.asc
│   ├── emoji-twitter-0.16.0-SNAPSHOT.module
│   ├── emoji-twitter-0.16.0-SNAPSHOT.module.asc
│   ├── emoji-twitter-0.16.0-SNAPSHOT.pom
│   ├── emoji-twitter-0.16.0-SNAPSHOT.pom.asc
│   └── maven-metadata-local.xml
└── maven-metadata-local.xml
emoji-twitter-android
├── 0.16.0-SNAPSHOT
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT-javadoc.jar
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT-javadoc.jar.asc
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT-sources.jar
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT-sources.jar.asc
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT.aar
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT.aar.asc
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT.module
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT.module.asc
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT.pom
│   ├── emoji-twitter-android-0.16.0-SNAPSHOT.pom.asc
│   └── maven-metadata-local.xml
└── maven-metadata-local.xml
emoji-twitter-jvm
├── 0.16.0-SNAPSHOT
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT-javadoc.jar
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT-javadoc.jar.asc
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT-sources.jar
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT-sources.jar.asc
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT.jar
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT.jar.asc
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT.module
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT.module.asc
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT.pom
│   ├── emoji-twitter-jvm-0.16.0-SNAPSHOT.pom.asc
│   └── maven-metadata-local.xml
└── maven-metadata-local.xml

3 directories, 38 files
```

Also tried that version via `mavenLocal()` with an app of mine and everything works too!

**Comment by gabrielittner** [comment]
Thanks for testing. There is one more thing that I want to look into and then we can do a release tomorrow or the beginning of next week
