### ISSUE TITLE
Gradle detecting problems with publish and sign dependencies for a multiplatform project

### ISSUE THREAD

**Issue by AlecStrong** [vanniktech/gradle-maven-publish-plugin#338]
If I run a publish task for a module which depends on another module
```
Gradle detected a problem with the following location: '~/Development/sqldelight/runtime/build/libs/runtime-2.1.0-SNAPSHOT-javadoc.jar.asc'. Reason: Task ':runtime:publishIosArm32PublicationToInstallLocallyRepository' uses this output of task ':runtime:signIosX64Publication'
```

This _might_ actually be a bug with gradle or kotlin but its hard to tell. It looks like the publish task references the jar signature file, which got signed by a previous task, so gradle expects there to be a task dependency?

**Comment by gabrielittner** [comment]
It might be https://youtrack.jetbrains.com/issue/KT-46466 which I opened a long time ago but I'll take a look again what could be causing it.

**Comment by eygraber** [comment]
Unfortunately I didn't copy the pertinent info from the log and GitHub deleted it, but I believe this is the same issue https://github.com/vanniktech/gradle-maven-publish-plugin/issues/259

**Comment by gabrielittner** [comment]
Added the workaround from the youtrack ticket directly to the plugin so that you don't need to apply it manually on each project
