### ISSUE TITLE
Support Android libraries in maven-publish mode

### ISSUE THREAD

**Issue by gabrielittner** [vanniktech/gradle-maven-publish-plugin#34]
Just opening this to have something open to track it.

From #32:
> Android libraries aren't supported right now with `useMavenPublish = true`. We'd need a SoftwareComponent implementation for those which is tracked here: https://issuetracker.google.com/issues/37055147. Which is blocked by https://github.com/gradle/gradle/issues/1842. The latter is also preventing us of providing our own implementation of SoftwareComponent unless we're ok with internal APIs. Here is an example of how to do it without SoftwareComponent, but for Android adding the dependencies to the pom is more complex.

**Comment by vanniktech** [comment]
@gabrielittner seems like 3.6.0-alpha07 will bring this

**Comment by ZacSweers** [comment]
It's available now!
