### ISSUE TITLE
Set publish repository for variant

### ISSUE THREAD

**Issue by thebino** [vanniktech/gradle-maven-publish-plugin#341]
Is there a way to configure the publish target repository per variant?

```kotlin
mavenPublish {
    androidVariantToPublish = "freeRelease"
}

mavenPublishing {
    publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.S01)
}
```

Now I'm looking for a solution, to publish the free version to S1 and another version (paidRelease) to an github with authentication.

I've seen #23 which is a starting point but not a solution.

Also #293  looks promising but couldn't resolve `AndroidMultiVariantLibrary` with version 0.18.0.

**Comment by gabrielittner** [comment]
In general this won't be possible based on how Gradle publishing works. Gradle will create separate tasks for the combination of each publication and each repository so you can get the behavior by creating multiple publications manually and then calling the right `publish<Publication Name>To<Repo name>Repository task.

> Also https://github.com/vanniktech/gradle-maven-publish-plugin/pull/293 looks promising but couldn't resolve AndroidMultiVariantLibrary with version 0.18.0.

It was only added in version 0.19.0, but multi variant libraries just publish multiple variants together.
