### ISSUE TITLE
Not able to publish only release version

### ISSUE THREAD

**Issue by abrolrahul** [vanniktech/gradle-maven-publish-plugin#346]
Hi Team,

I have upgraded this plugin to the recent version which is `0.19.0` after the update both debug and release versions are getting published. Ideally, it should be `xyz:1.0.0@aar` but its now publishing `xyz:1.0.0-debug@aar` & `xyz:1.0.0-release@aar`. Please let me know how to fix it?

**Comment by BlackMesa123** [comment]
As specified in the [changelog](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/CHANGELOG.md#version-0190-2022-02-26), you can use the androidVariantToPublish flag to revert to the old behavior:
```groovy
mavenPublish {
    sonatypeHost = "S01"
    androidVariantToPublish = "release"
}
```

**Comment by gabrielittner** [comment]
What's the reason for not wanting to publish it as a multi variant library?

**Comment by gabrielittner** [comment]
0.21.0 is only publishing release, but we're planning to make multi variant publishing the default again in the future, so it would be interesting to know your reasoning

**Comment by BlackMesa123** [comment]
Personally I don't need to publish all the variants in [my Android library](https://github.com/OneUIProject/oneui-core) since I only have debug and release, so publishing only the release variant imho is better
