### ISSUE TITLE
0.20.0 changelog is confusing

### ISSUE THREAD

**Issue by eygraber** [vanniktech/gradle-maven-publish-plugin#355]
The changelog for 0.20.0 says that we should use:

```
mavenPublishing {
  publishToMavenCentral() // use publishToMavenCentral("S01") for publishing through s01.oss.sonatype.org
  enableReleaseSigning()
}
```

but the closest I could get it to working is:

```
mavenPublishing {
  publishToMavenCentral(SonatypeHost.S01)
  signAllPublications()
}
```

I'm not sure if that results in the correct behavior though.

**Comment by gabrielittner** [comment]
Are you using `kts` or regular groovy build files?

**Comment by gabrielittner** [comment]
Also, do you want to `oss.sonatype.org` or `s01.oss.sonatype.org`?

**Comment by eygraber** [comment]
I'm using `kts` and I want `s01`

**Comment by gabrielittner** [comment]
Fixed this in the 0.21.0 changelog

**Comment by eygraber** [comment]
After updating to 0.21.0 there is still no `enableReleaseSigning` function available. `signAllPublications` continues to work.

**Comment by gabrielittner** [comment]
Completely missed that second part of your message 🤦 It's fixed now https://github.com/vanniktech/gradle-maven-publish-plugin/commit/9b9cbaa684bc254c73dd4640c10d313d1b758b38 Thanks
