### ISSUE TITLE
GPG 2.3+ format clash

### ISSUE THREAD

**Issue by steve-the-edwards** [vanniktech/gradle-maven-publish-plugin#377]
I am having trouble publishing locally after upgrading GPG past 2.1 on a new computer where I no longer have `secring.gpg` and I am not sure where to point the plugin to find the secret key in the `~/.gnupg/private-keys-v1.d` folder as per the new format. See https://github.com/gpg/gnupg/blob/master/agent/keyformat.txt 

Any ideas on options here other than downgrading GPG? How difficult is it to support updated GPG format?

**Comment by steve-the-edwards** [comment]
The workaround (very workable) is:
```
gpg --export-secret-key <YOUR-KEY-ID> > secring.gpg
```

So not a big concern I realize.

**Comment by gabrielittner** [comment]
That is the solution I went with as well. The 2 alternatives are in memory keys (mostly meant for CI) and pointing Gradle to a gpg agent https://docs.gradle.org/7.4.2/userguide/signing_plugin.html#sec:using_gpg_agent

Signing is in general handled by Gradle and there is this long standing issue for this https://github.com/gradle/gradle/issues/888
