### ISSUE TITLE
Provision to specify timeout for closing repository on maven

### ISSUE THREAD

**Issue by PatilShreyas** [vanniktech/gradle-maven-publish-plugin#378]
## Introduction

When the sonatype host took a lot of time to respond while running the `closeAndReleaseRepository`, the exception occurred twice. So there must be a configuration to specify a timeout, which will be really helpful.

## Crash

```
> Task :closeAndReleaseRepository FAILED
FAILURE: Build failed with an exception.
1 actionable task: 1 executed

* What went wrong:
Execution failed for task ':closeAndReleaseRepository'.
> java.net.SocketTimeoutException: timeout
```

Refer this CI log for more information: https://github.com/PatilShreyas/mutekt/runs/7598566694?check_suite_focus=true

**Comment by FZambia** [comment]
Same for me: https://github.com/centrifugal/centrifuge-java/runs/8055949219?check_suite_focus=true

**Comment by gabrielittner** [comment]
Timeouts have been increased by a lot for the next release

**Comment by vegaro** [comment]
We have started to get timeouts again, not sure it's isolated or just us, but it would be ideal if we could get a Gradle property or something exposed so we had more control on this and we didn't have to wait for a release to increase the timeouts.

Thanks!

**Comment by gabrielittner** [comment]
Definitely open to adding an option but right now the situation for oss.sontatype.org is so bad that even longer time outs don't help much if at all
