### ISSUE TITLE
Don't sign `publishToMavenLocal`

### ISSUE THREAD

**Issue by BraisGabin** [vanniktech/gradle-maven-publish-plugin#383]
Is there a way to make `publishToMavenLocal` without signing it? I know

## My use case

I'm developing https://github.com/detekt/detekt-custom-rule-template. Right now this template promotes the usage of Jitpack as an straight forward option to share your detekt rules. But, since that's a good strating point it's difficult to migrate from jitpack to Maven Central. For that reason I want to integrate this plugin in the template to make that step easier.

The problem is that out of the box this plugin doesn't works well with jitpack because jitpack executes `./gradlew publishToMavenLocal` on the root project and takes the jar from there. And, because the properties related with the signing are not there (they should be stored as secrets) the upload to jitpack fails.

There is other use case and is that I would like to execute `publishToMavenLocal` on my CI as a PR check. This way I can spot publish issues before I want to make a release. And I would like to do that without uploading secrets to the repository.

**Comment by gabrielittner** [comment]
Depending on whether you enable signing with `RELEASE_SIGNING_ENABLED` or `signAllPublications()` you can just not set that property or not call that method in situations where you don't want to sign. So you could for example generally not set it but then when you want to sign do `./gradlew publish -PRELEASE_SIGNING_ENABLED=true`
