### ISSUE TITLE
Task closeAndReleaseRepository has timeout

### ISSUE THREAD

**Issue by Daphne-CoffeeIT** [vanniktech/gradle-maven-publish-plugin#385]
I've been using this plugin for over a year and it has always worked very nicely. However, since today I can't close and release repositories no more. I've tried over ten times and the task will run for about 15 minutes and then I get a timeout. I did not change my configuration and I'm using the latest version of the plugin.

Did something break? Is this happening due to slow Sonatype servers? Can it be fixed on our side?

Running:
```
> Task :closeAndReleaseRepository
Closing repository: [REDACTED]
⠇ waiting for close...
<-------------> 0% EXECUTING [12m 44s]
> :closeAndReleaseRepository
```

Timeout:
```
> Task :closeAndReleaseRepository
Closing repository: [REDACTED]
⠇ waiting for close...
> Task :closeAndReleaseRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':closeAndReleaseRepository'.
> java.io.IOException: Timeout waiting for repository close
```

**Comment by vanniktech** [comment]
I've gotten the same. https://github.com/vanniktech/RxPermission/runs/7904350124?check_suite_focus=true

Maybe the API has changed? I was able to close & release using https://oss.sonatype.org/

**Comment by Daphne-CoffeeIT** [comment]
So you do have problems with https://s01.oss.sonatype.org/ but not with https://oss.sonatype.org/? I'm also using https://s01.oss.sonatype.org/.

**Comment by vanniktech** [comment]
Yes I closed and released my failed release from CI manually via v

**Comment by Daphne-CoffeeIT** [comment]
I tried that too and it worked. Then I tried it again via the plugin and it worked again. I didn't change any code and I really don't have a clue what happened 😅

**Comment by FZambia** [comment]
Got the same over `oss.sonatype.org`, is there a way to increase timeout? possibly over an environment variable?
