### ISSUE TITLE
Signing of files not done by publish command and closeAndReleaseRepository command not working

### ISSUE THREAD

**Issue by gautamgiri-dev** [vanniktech/gradle-maven-publish-plugin#388]
I tried uploading library to mavenCentral with all the required details like signingId signingPassword signingKeyFile. But after uploading, when manually closing the repository on Nexus Repository system the signature validation fails as *.asc files are not generated.

![image](https://user-images.githubusercontent.com/65446143/187044293-3140b6b1-b7d2-42d2-95ed-bce0d862f0e0.png)

**Comment by vanniktech** [comment]
Did you set `RELEASE_SIGNING_ENABLED=true`?

**Comment by gautamgiri-dev** [comment]
Thanks You @vanniktech . adding `RELEASE_SIGNING_ENABLED=true` solved the issue.
