### ISSUE TITLE
Support for adding multiple developers information

### ISSUE THREAD

**Issue by gautamgiri-dev** [vanniktech/gradle-maven-publish-plugin#389]
If a library is having more than one developers how can we configure that in `gradle.properties` to produce `pom` xml containing the information of all developers?

![image](https://user-images.githubusercontent.com/65446143/187067485-7363d250-5060-442d-9bb0-013f7d033c16.png)

**Comment by vanniktech** [comment]
Use the base plugin with kotlin dsl: https://github.com/vanniktech/gradle-maven-publish-plugin#base-plugin

```
                developers {
                    developer {
                        id = "username"
                        name = "User Name"
                        url = "https://github.com/username/"
                    }
                }
```
