### ISSUE TITLE
[QUESTION] Is there a way to get version from the last commit tag?

### ISSUE THREAD

**Issue by raamcosta** [vanniktech/gradle-maven-publish-plugin#390]
It seems possible with base plugin, but I'm not sure I want to jump into that, since I have a setup in gradle.properties working 😄 
But it would be nice if I could set the version of my libraries without manually changing gradle.properties.

Sorry for the newbie question, I'm a newb at gradle 😅

**Comment by gabrielittner** [comment]
You can pass the version name as a Gradle property from command line when you call the publish task. For example `./gradlew publish -PVERSION_NAME="$(git describe)"`. It is also possible to create an env var called `ORG_GRADLE_PROJECT_VERSION_NAME` with a computed value which works well on CI
