### ISSUE TITLE
Task uploadArchives looping in Kotlin artifacts.

### ISSUE THREAD

**Issue by WellingtonCosta** [vanniktech/gradle-maven-publish-plugin#40]
When I try to upload a multi module project that has a Kotlin module, the `uploadArchives` task enter in loop and I need to force stop it.

 Any idea?

**Comment by vanniktech** [comment]
Are you using the Daemon or the parallel flag? Usually, I disable those while uploading.

**Comment by WellingtonCosta** [comment]
I'm using parallel flag... Would be it?

**Comment by vanniktech** [comment]
Yeah. Try not using it. It should work. Might be worth pointing that out in the README. Want to submit a PR?

**Comment by WellingtonCosta** [comment]
Ok. I'll try to do that without the parallel flag. If it works, I'll  submit a PR describing this issue in README.

**Comment by WellingtonCosta** [comment]
It worked:

```
org.gradle.daemon=false
org.gradle.parallel=false
```

I'm sending a PR describing this in README.md.

**Comment by vanniktech** [comment]
Fixed by #41
