### ISSUE TITLE
Drop an automatically created sonatype staging repo if there is a build failure

### ISSUE THREAD

**Issue by eygraber** [vanniktech/gradle-maven-publish-plugin#406]
If a sonatype staging repo is automatically created, but the build ends up failing for some reason, there will be a buildup of empty staging repos in nexus. If those could be dropped when the build fails that would be very helpful.

**Comment by gabrielittner** [comment]
This will be done on a best effort basis in in 0.22.0. So the plugin will try to drop it after build failures but will not do anything in case that fails.
