### ISSUE TITLE
Library dependency not found

### ISSUE THREAD

**Issue by AgneseBussone** [vanniktech/gradle-maven-publish-plugin#407]
Hello,
I'm releasing my library to Maven Central using this plugin. Everything worked as expected and I was able to upload to the snapshot repository. 
Now I'm trying to use my library in a new project as external dependency, but one of the library's dependencies is distributed through JitPack and unless I add it to the repository list in the app, this dependency is not found.

I was wondering if there is a way to configure the pom file or some other file to resolve all the dependency my library needs without asking my users to add jitpack to their repository list.

Thank you.

**Comment by gabrielittner** [comment]
This is not possible from the Gradle side. My advice would be to request the authors of that dependency to publish to maven central as well.
