### ISSUE TITLE
v0.22.0 is automatically closing non-staging artifacts

### ISSUE THREAD

**Issue by dlew** [vanniktech/gradle-maven-publish-plugin#426]
Call me old fashioned but I prefer to manually close & release artifacts... as a result, I discovered the latest version (0.22.0) automatically closes when you call `./gradlew publish --no-daemon --no-parallel`.

The logs seem to indicate that it is trying to create & close the *staging* repository, but in reality it's closing the *prod* repository:

```
> Task :library:createStagingRepository
Creating repository in profile: net.danlew
Created staging repository netdanlew-1065
Closing repository: netdanlew-1065
⠴ waiting for close...                                               Repository netdanlew-1065 closed
```

Here's what I opened OSS sonatype to see:

![image](https://user-images.githubusercontent.com/514850/192147195-3df6acf4-f28c-42f1-9aaf-45fe87d3ec7b.png)

**Comment by gabrielittner** [comment]
> The logs seem to indicate that it is trying to create & close the staging repository, but in reality it's closing the prod repository

When you publish a release version everything gets uploaded into a staging repository, releasing that repository will then sync it to maven central (production so to say), so the logs are correct.

> Call me old fashioned but I prefer to manually close & release artifacts... as a result, I discovered the latest version (0.22.0) automatically closes when you call ./gradlew publish --no-daemon --no-parallel.

0.22.0 has some changes around how the plugin uploads to sonatype staging repos to avoid creating multiple staging repos, this also makes the `--no-daemon --no-parallel` parameters obsolete. As part of those changes the staging repository gets closed automatically at the end of the build if there were no failures. It will not get released automatically however this is still a manual step unless you enable the option to also automate it. The reason why automatic closing isn't opt-in and why there is also no option to disable it is that there isn't really any irreversible harm in it. You can still review what was uploaded before releasing and if there is something wrong with it drop it.

**Comment by dlew** [comment]
That all sounds reasonable to me - maybe this is more of a documentation issue than anything else then. I was basing things off of [these statements](https://github.com/vanniktech/gradle-maven-publish-plugin#releasing) which show `--no-daemon --noparallel` and also has the task `closeAndReleaseRepository`, both of which a outdated/misnomers  no.

**Comment by gabrielittner** [comment]
I somehow missed that section, will update it 👍

**Comment by gabrielittner** [comment]
This is now covered in the new docs https://vanniktech.github.io/gradle-maven-publish-plugin/central/#publishing happy for feedback or prs in case anything is still missing or unclear.
