### ISSUE TITLE
mavenCentralUsername mavenCentralPassword exclude from git

### ISSUE THREAD

**Issue by dmytro1morozov** [vanniktech/gradle-maven-publish-plugin#432]
I've added the general configuration for the project in /rootProjectDir/gradle.properties.
In /rootProjectDir/library/gradle.properties module's props, I've added each library's specific configuration, like POM_ARTIFACT_ID, POM_NAME, VERSION_NAME
I cannot add mavenCentralUsername and mavenCentralPassword to a separate file, like into /rootProjectDir/library/gradle.properties or /rootProjectDir/library/gradle.properties or /rootProjectDir/library/maven.properties or /rootProjectDir/.gradle/gradle.properties in order to exclude maven access credentials. How can I do that?
I don't want to set env variables as the credentials may clash from project to project

**Comment by gabrielittner** [comment]
You have multiple options:
- put them into `~/.gradle/gradle.properties` this way they are outside of the project on your machine
- export them as environment variables called `ORG_GRADLE_PROJECT_mavenCentralUsername` and `ORG_GRADLE_PROJECT_mavenCentralPassword`
- pass them in from command line when running the publish task `./gradlew publish -PmavenCentralUsername=... -PmavenCentralPassword=...`

**Comment by dmytro1morozov** [comment]
@gabrielittner , I tried with ~/.gradle/gradle.properties approach and that should solve my issue, but unfortunately moving all the information from rootDir/gragle.properties to ~/.gradle/gradle.properties removes the task publish and release/closeAndReleaseRepository. So i am unable to release my library when storing authentication in  ~/.gradle/gradle.properties

**Comment by dmytro1morozov** [comment]
If i move only credentials into ~/.gradle/gradle.properties and leave all the configuration under rootDir/gradle.properties, then the credentials are not used and the following error is received:

```Credentials required for this build could not be resolved.
> The following Gradle properties are missing for 'mavenCentral' credentials:
    - mavenCentralUsername
    - mavenCentralPassword```

**Comment by dmytro1morozov** [comment]
I've resolved the issue by setting Gradle home folder in Android studio to /home/user/.gradle. 

Here is some related description
https://discuss.gradle.org/t/gradle-gradle-properties-file-not-being-read/7574

**Comment by dmytro1morozov** [comment]
However, in this case it is possible to set up gradle.properties only once. If you have multiple projects to be published to maven, you will have to use single /home/.gradle/gradle.properties file and replace it with appropriate one each time.

**Comment by dmytro1morozov** [comment]
It would be great if it was possible to put credentials in 

projectDir/.gradle/gradle.properties
