### ISSUE TITLE
Cannot get stagingProfiles

### ISSUE THREAD

**Issue by RohitVerma882** [vanniktech/gradle-maven-publish-plugin#443]
> Task :cxx:bundleReleaseAar UP-TO-DATE                    Caching disabled for task ':cxx:bundleReleaseAar' because:   Build cache is disabled                                  Skipping task ':cxx:bundleReleaseAar' as it is up-to-date. :cxx:bundleReleaseAar (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 0.02 secs.                   :cxx:createStagingRepository (Thread[Execution worker for ':' Thread 5,5,main]) started.                                                                                         > Task :cxx:createStagingRepository                        Caching disabled for task ':cxx:createStagingRepository' because:                                                       Build cache is disabled                                  Task ':cxx:createStagingRepository' is not up-to-date because:                                                          Task has not declared any outputs despite executing actions.                                                                                                                   > Task :cxx:createStagingRepository FAILED                 :cxx:createStagingRepository (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 3.411 secs.                                                                      FAILURE: Build failed with an exception.                                                                              * What went wrong:                                         Execution failed for task ':cxx:createStagingRepository'.  > java.io.IOException: Cannot get stagingProfiles for account RohitVerma882 :

**Comment by gpeal** [comment]
@RohitVerma882 How did you fix this?

**Comment by jiangjm424** [comment]
also get this error

**Comment by RohitVerma882** [comment]
replace your userName and password with userName and password tokens

**Comment by jiangjm424** [comment]
> also get this error

sorry , i have changed the publishToMavenCentral() to publishToMavenCentral(SonatypeHost.S01), and it has resolved.
