### ISSUE TITLE
Is workaround still needed for [KMP Publishing task dependencies]?

### ISSUE THREAD

**Issue by eygraber** [vanniktech/gradle-maven-publish-plugin#457]
Does 0.22.0 fix [KT-46466](https://youtrack.jetbrains.com/issue/KT-46466)? There's something in the release notes, but it doesn't mention that issue specifically?

If yes, then I should be able to remove my workaround, right?

```
public fun Project.fixPublishTaskImplicitDependencyOnSigningTasks() {
  val signingTasks = tasks.withType(Sign::class.java)
  tasks.withType(AbstractPublishToMaven::class.java).configureEach {
    dependsOn(signingTasks)
  }
}
```

**Comment by gabrielittner** [comment]
The workaround is not needed anymore on your side, the plugin will automatically apply it when signing gets enabled https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt#L135-L138

I'll add a link to the youtrack issue to the release notes
