### ISSUE TITLE
[Request] Add mavenCentralUsername and mavenCentralPassword as publishToMavenCentral parameters

### ISSUE THREAD

**Issue by GuilhE** [vanniktech/gradle-maven-publish-plugin#459]
I want to move `mavenCentralUsername` and `mavenCentralPassword` from the global `~/.gradle/gradle.properties` to my project `local.properties`. I could accomplish it for the signing credentials:

```
signing {
    val signingInMemoryKeyId: String
    val signingInMemoryKey: String
    val signingInMemoryKeyPassword: String

    if (project.rootProject.file("local.properties").exists()) {
        with(Properties().apply { load(FileInputStream(File(rootProject.rootDir, "local.properties"))) }) {
            signingInMemoryKeyId = getProperty("signingInMemoryKeyId")
            signingInMemoryKey = getProperty("signingInMemoryKey")
            signingInMemoryKeyPassword = getProperty("signingInMemoryKeyPassword")
        }
    } else {
        signingInMemoryKeyId = System.getenv("ORG_GRADLE_PROJECT_signingInMemoryKeyId")
        signingInMemoryKey = System.getenv("ORG_GRADLE_PROJECT_signingInMemoryKeyId")
        signingInMemoryKeyPassword = System.getenv("ORG_GRADLE_PROJECT_signingInMemoryKeyPassword")
    }
    useInMemoryPgpKeys(signingInMemoryKeyId, signingInMemoryKey, signingInMemoryKeyPassword)
}
```
But since I cannot provide this parameters like in `useInMemoryPgpKeys()` and looking at [this](https://tomgregory.com/gradle-project-properties-best-practices/):
![imagem](https://user-images.githubusercontent.com/2677139/206879278-42ef458a-4d72-40d4-b319-30ee7ff16048.png)

It doesn't seem to be possible. Unless of course you update `publishToMavenCentral` to allow passing this values as parameters (leaving the current logic as default). Actually the same logic could be applied to `signAllPublications()` because now I'm using the `signing` extension which will override yours I believe.

**Comment by gabrielittner** [comment]
We are using Gradle's credential API to configure the repository as described here https://docs.gradle.org/current/samples/sample_publishing_credentials.html. Please file a feature request with Gradle to support a project local way of providing credentials
