### ISSUE TITLE
Kotlin files are not included to sources jar

### ISSUE THREAD

**Issue by lukaville** [vanniktech/gradle-maven-publish-plugin#47]
[Here](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/groovy/com/vanniktech/maven/publish/MavenPublishPlugin.groovy#L69) we configure androidSourcesJar with `project.android.sourceSets.main.java.sourceFiles` which doesn't contain kotlin source code. So resulting sources.jar includes only java files for kotlin projects.

Probably we should replace it with `project.android.sourceSets.main.java.srcDirs`?

**Comment by vanniktech** [comment]
Probably. This can also fix the issue pointed out by @ZacSweers

**Comment by vanniktech** [comment]
@lukaville let's make this change. Do you want to submit a PR or should I?
