### ISSUE TITLE
Add lifecycle-level logging of staging repository name

### ISSUE THREAD

**Issue by JakeWharton** [vanniktech/gradle-maven-publish-plugin#472]
This allows me to explicitly close/drop using GitHub Actions which are dispatched using workflow_dispatch and which accept the name as an input.

I think it also allows me to also use the staging repository via URL?

**Comment by JakeWharton** [comment]
Dropping would require #450

**Comment by gabrielittner** [comment]
We do already have some logs as simple `println` (they are in a Gradle independent module) but we can update it to go through Gradle's logger. [This log](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/nexus/src/main/kotlin/com/vanniktech/maven/publish/nexus/Nexus.kt#L79) is probably the one you'd want, the `$id` printed there is the same as the optional `--repository` parameter for the release task. 

> Dropping would require https://github.com/vanniktech/gradle-maven-publish-plugin/issues/450

I'll probably look at that one next week

**Comment by JakeWharton** [comment]
Oh I didn't see those, but I wouldn't want to run Gradle at the level where those would be displayed since Gradle is a ridiculously noisy thing. I thought that it would probably go immediately after this line: https://github.com/vanniktech/gradle-maven-publish-plugin/blob/f79a433d768ee87944ba54aa010297ba5ecba810/plugin/src/main/kotlin/com/vanniktech/maven/publish/sonatype/CreateSonatypeRepositoryTask.kt#L40. I figure since publication is a rare thing and not a normal task that runs during a normal build it would be okay to log at the lifecycle level (where the bar for showing things is _extremely_ high).

**Comment by gabrielittner** [comment]
I can add one there 👍

**Comment by gabrielittner** [comment]
I can actually see the println with Gradle's default log level (just running `./gradlew publish` without options)
<img width="445" alt="Screenshot 2022-12-23 at 21 09 13" src="https://user-images.githubusercontent.com/1358105/209401515-b477eaaf-1cce-4f19-a08b-887016edc311.png">
https://github.com/freeletics/mad/actions/runs/3530272586/jobs/5922087004

**Comment by JakeWharton** [comment]
Huh!

So when I found that `println` in the source I searched for "created" in our release action and got no results. But I just tried it again, and GitHub does not search within logs _unless_ you expend the steps first. Once I expand the Gradle step the search works 🤦.

Okay so sounds like no action to take here then!

**Comment by gabrielittner** [comment]
Closing this then 👍
