### ISSUE TITLE
Add remaining integration tests

### ISSUE THREAD

**Issue by vgaidarji** [vanniktech/gradle-maven-publish-plugin#50]
Integration tests were introduced in #49, but not for every unit test appropriate integration test was added to keep original PR shorter and easier to review.
Add following integration tests:
- [ ] Android library
- [ ] Android library + Kotlin Android
- [ ] Java library + Kotlin

**Comment by gabrielittner** [comment]
Has been addressed in #78 and #18

**Comment by vgaidarji** [comment]
@gabrielittner I'm not sure though #78 and #18 cover all remaining projects configurations.

Was it discussed somewhere that having integration tests for following project configurations brings no value?
- [ ] Android library
- [ ] Android library + Kotlin Android
- [ ] Java library + Kotlin

Project has no such tests at the moment and no corresponding fixtures
![image](https://user-images.githubusercontent.com/3036347/72735636-e0c67800-3ba4-11ea-8e44-dfaaa8356870.png)

**Comment by gabrielittner** [comment]
What exactly do you mean? `passing_android_project` is the fixture for Android library, `passing_android_with_kotlin_project` the one for Android library + Kotlin Android

**Comment by vgaidarji** [comment]
@gabrielittner oh you're right, sorry. Ignore the comment above, took a closer look at https://github.com/vanniktech/gradle-maven-publish-plugin/pull/80 and everything is there 👍.
