### ISSUE TITLE
Upgrade to 0.24.0 fails with kotlinSourcesJar error

### ISSUE THREAD

**Issue by yschimke** [vanniktech/gradle-maven-publish-plugin#510]
Upgrade to 0.24.0 failure

https://github.com/square/okhttp/pull/7673

```
* What went wrong:
Task with name 'kotlinSourcesJar' not found in project ':okcurl'.
```

I'll look into this in next few days, but flagging in case it's affecting others or the fix is simple.

**Comment by gabrielittner** [comment]
I think the issue is that it uses `KotlinJvm` [here](https://github.com/square/okhttp/blob/master/okcurl/build.gradle.kts#L111) but it is a multiplatform project. Was that intentional?

**Comment by yschimke** [comment]
Thanks, will fix.
