### ISSUE TITLE
Sonatype tasks should ideally use Gradle workers

### ISSUE THREAD

**Issue by JakeWharton** [vanniktech/gradle-maven-publish-plugin#516]
This allows them to operate in parallel with other tasks in the same project. The most important one is the create staging repository task as it currently blocks other tasks (such as regular compilation) from running. The build service and normal task dependencies ensuring ordering remains correct.

https://docs.gradle.org/current/userguide/worker_api.html#converting_to_the_worker_api

**Comment by gabrielittner** [comment]
👍 makes sense. Configuration cache in Gradle 8 would also solve this but who knows how long it takes until the missing parts that we need are resolved on the Gradle side

**Comment by gabrielittner** [comment]
Only added it for the create task. In a build with automatic publishing the close and release steps will happen directly in the build service after all tasks completed, so there is nothing for workers here. The standalone closeAndRelease task and the the drop task could also get it but they are usually run in separate Gradle invocations and the usually on their own.  Let me know though if there is a use case for these that I'm not considering.

**Comment by JakeWharton** [comment]
Nope. Thanks for the speedier release builds!
