### ISSUE TITLE
sonatype is slow.  any way to upload in parallel?

### ISSUE THREAD

**Issue by deanhiller** [vanniktech/gradle-maven-publish-plugin#55]
I read about needing to run

./gradlew uploadArchives --no-daemon --no-parallel

Any way to run in parallel since sonatype is slow.

ALSO, does this work with sonatype which is for publishing to some open source repo (I just know it ends up here https://mvnrepository.com/artifact/org.webpieces)

thanks,
Dean

**Comment by vanniktech** [comment]
I haven't found a way to speed it up. I guess it's worth asking on the Gradle issue tracker since we're just using their plugin.

Yeah. You can publish it to any arbitrary repository. https://github.com/vanniktech/gradle-maven-publish-plugin/pull/9
