### ISSUE TITLE
Inquiry: Thoughts on passing arguments for `closeAndReleaseRepository` task

### ISSUE THREAD

**Issue by 05nelsonm** [vanniktech/gradle-maven-publish-plugin#551]
With the last couple of Sonatype outages over the past months due to high volume, I was hoping to get thoughts on the ability to pass arguments (the repository ids) via command line for a bulk release.

The current `closeAndReleaseRepository` task queries the same API that the web GUI staging repository does (which was what was causing the outages), in order to retrieve all the closed repository id's that are ready for releasing. Then the task perform the bulk release. That query to the API that has been causing trouble can be skipped though if you know the repository id's (which are output to terminal when publishing).

```bash
# Example repository id: iomatthewnelson-1018

$ curl -v -u "<USER NAME>" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  https://s01.oss.sonatype.org/service/local/staging/bulk/promote --data '
  {
    "data": {
      "stagedRepositoryIds": [
        "<repository id>",
        "<repository id>"
      ],
      "autoDropAfterRelease": true
    }
  }'
```

What if we could pass in via command line arguments the `repository-id`'s, which would skip the query for them and only target bulk release for those?

Something like
```bash
./gradlew closeAndReleaseRepository -DREPOSITORY_IDS="iomatthewnelson-1018,iomatthewnelson-1019"
```

**Comment by gabrielittner** [comment]
The task already has an option for this, but I forgot to add it to the docs and it only supports one repository at a time. It's defined [here](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/plugin/src/main/kotlin/com/vanniktech/maven/publish/sonatype/CloseAndReleaseSonatypeRepositoryTask.kt#L19-L22) and can be used like this `./gradlew closeAndReleaseRepository --repository=comexample-123`. According to the [docs](https://docs.gradle.org/current/userguide/custom_tasks.html#sec:declaring_and_using_command_line_options) we could change that to a `List<String>` which would allow passing in multiple repositories, enabling this looks good to me. 

However currently it will fetch the repository by its id to see the current status, if it is still open it will call `staging/bulk/close` (waiting until it has closed will make more calls) and afterwards or if already was closed it will call `staging/bulk/promote`. So in the best case the it would be 2 calls if the repository was already closed and if it wasn't then it would be 4+.

**Comment by gabrielittner** [comment]
Closing this because as mentioned above that specifying the repositories to close does not significantly reduce the number of requests.
