### ISSUE TITLE
Publish kotlin-jar only works for snapshots

### ISSUE THREAD

**Issue by opensource21** [vanniktech/gradle-maven-publish-plugin#56]
I try to publish https://gitlab.com/ppiag/kzulip to maven central.
It works fine for [snapshots](https://oss.sonatype.org/content/groups/staging/de/ppi/oss/kzulip/)
but not for stable-releases. 
I don't get any error-message.
With maven it [works fine](https://oss.sonatype.org/content/groups/staging/de/ppi/oss/zulip-const/) and is in [maven-central](https://search.maven.org/artifact/de.ppi.oss/zulip-const/0.1.3/jar).
What could be wrong?

**Comment by opensource21** [comment]
Found it at https://oss.sonatype.org/#stagingRepositories. seems that the steps from https://central.sonatype.org/pages/releasing-the-deployment.html must be manual. The maven plugin does it automatic.
Can you confirm this assumption and perhaps improve the documentation?

**Comment by vanniktech** [comment]
Ups. Sorry. I lost this along the way.

> Can you confirm this assumption and perhaps improve the documentation?

Yes, your assumption is correct. Mind creating a PR and improve the README?

**Comment by opensource21** [comment]
PR is created. Would be great if this step could be automated too, shall I create a new issue as feature request?

**Comment by vanniktech** [comment]
Sure!
