### ISSUE TITLE
Disable javadoc generation

### ISSUE THREAD

**Issue by p-dmitriy** [vanniktech/gradle-maven-publish-plugin#565]
How can I disable javadoc generation and publishing? There is an `AndroidSingleVariantLibrary` class that have `publishJavadocJar` parameter with default value `true`. And single usage of that class does not allow to override this parameter.

Also how I can see there is no way to replace publishing variant `AndroidSingleVariantLibrary` with multiple variants. If I declare multiple variants in android block, single variant still will be added by plugin.

**Comment by p-dmitriy** [comment]
Found that I need to use base plugin. It is not obviously, why did you not made single plugin but configurable?

**Comment by gabrielittner** [comment]
This will properly work without having to use base plugin in the next release
