### ISSUE TITLE
Support publishing of Kotlin Multiplatform projects

### ISSUE THREAD

**Issue by Egorand** [vanniktech/gradle-maven-publish-plugin#57]
Might use SQLDelight's [gradle-mvn-mpp-push.gradle](https://github.com/square/sqldelight/blob/master/gradle/gradle-mvn-mpp-push.gradle) as a prototype. Can try to find time to implement this.

**Comment by vanniktech** [comment]
That would be lovely. We also have proper integration tests now in place which should make this easier

**Comment by gabrielittner** [comment]
FYI I'm working on this. Initial implementation can be found here https://github.com/vanniktech/gradle-maven-publish-plugin/compare/master...gabrielittner:mpp
