### ISSUE TITLE
Using Base plugin in the project's root causes NPE

### ISSUE THREAD

**Issue by SandraZiv** [vanniktech/gradle-maven-publish-plugin#599]
Hi, I have a multimodule Android library that I would like to publish. In order to get more control over what is being published, I used  [Base plugin](https://vanniktech.github.io/gradle-maven-publish-plugin/base/#android-library-single-variant). It works fine when I place the code in every module's `build.gradle.kts`, but that makes a lot of code duplication, so I tried placing it in the project's root `build.gradle.kts,` and it gave me `java.lang.NullPointerException (no error message)`:

```
* Exception is:
java.lang.NullPointerException
	at com.vanniktech.maven.publish.AndroidSingleVariantLibrary.configure$plugin(Platform.kt:145)
	at com.vanniktech.maven.publish.MavenPublishBaseExtension.configure(MavenPublishBaseExtension.kt:338)
	at Build_gradle$5$3.execute(build.gradle.kts:112)
	at Build_gradle$5$3.execute(build.gradle.kts:111)
	... 
```

This is the code that I was trying to add in the project's root `build.gradle.kts`:
```
subprojects {
    apply(plugin = "com.vanniktech.maven.publish.base")

	mavenPublishing {
	        configure(
	            com.vanniktech.maven.publish.AndroidSingleVariantLibrary(
	                sourcesJar = false
	            )
	        )
    }
}
```

The question is, is this expected behavior? Is there a better way to overcome this kind of code duplication?

Thanks in advance 🙌

**Comment by gabrielittner** [comment]
When you call `configure` in the base plugin it does expect other plugins to be applied already. The NPE in this case happens because your call is before the Android plugin was applied. What you can do is to move the `apply(plugin = "com.vanniktech.maven.publish.base")` to the suprojects and then change the config in your root to
```
subprojects {
    plugins.withId("com.vanniktech.maven.publish.base") {
        mavenPublishing {...}
    }
}

We should have a better error message for this though
```

**Comment by SandraZiv** [comment]
Got it, it works now, thanks for the help!

**Comment by gabrielittner** [comment]
We'll have a batter error message in the next version that will say that the com.android.library plugin needs to be applied when configure is called
