### ISSUE TITLE
Feature request: Support for shadowJar

### ISSUE THREAD

**Issue by hzsweers** [vanniktech/gradle-maven-publish-plugin#6]
https://github.com/johnrengelman/shadow

**Comment by hzsweers** [comment]
@gabrielittner has some prior work here: https://github.com/gabrielittner/auto-value-cursor/blob/master/auto-value-cursor/build.gradle#L9-L31

**Comment by vanniktech** [comment]
How would the API look like?

**Comment by hzsweers** [comment]
Looking more at gabriel's implementation, seems it wouldn't need explicit support. Nevermind then :)

**Comment by geomagilles** [comment]
@ZacSweers could you please tell us how did you manage to publish shadowJar?

**Comment by ZacSweers** [comment]
https://github.com/square/moshi/blob/master/kotlin/codegen/build.gradle.kts

**Comment by geomagilles** [comment]
> https://github.com/square/moshi/blob/master/kotlin/codegen/build.gradle.kts

Thx for the quick reply!
