### ISSUE TITLE
Repo creates but then 401 appears.

### ISSUE THREAD

**Issue by Merseyside** [vanniktech/gradle-maven-publish-plugin#600]
https://github.com/Merseyside/mersey-kmp-kotlin-ext/actions/runs/5443608828/jobs/9904318861

Here is my log. Repo successfully creates, I can face it in my nexus repo manager, then building fails on :initializeSonatypeStagingRepository task with 401 and repo disappears. Can you help me?

**Comment by gabrielittner** [comment]
The `initializeSonatypeStagingRepository` task comes from the gradle-nexus plugin which you are also applying. The successful `createStagingRepository` is from this plugin. If you remove the gradle-nexus plugin publishing should work

**Comment by Merseyside** [comment]
Oh, thanks so much! Didn't give an importance for that little thing. Now it works as expected.
