### ISSUE TITLE
Configuration failure when referencing built jar of module

### ISSUE THREAD

**Issue by msridhar** [vanniktech/gradle-maven-publish-plugin#625]
We are trying to update NullAway from plugin version 0.21.0 to the latest version, 0.25.3, but after updating, configuration fails.  To reproduce, check out https://github.com/msridhar/NullAway/tree/bump-gradle-maven-publish-to-0.25.3 and run `./gradlew --dry-run`.  This yields the following error:
```
A problem occurred evaluating project ':nullaway'.
> Could not create task ':nullaway:buildWithNullAway'.
   > Could not resolve all files for configuration ':nullaway:nullawayJar'.
      > Could not find com.uber.nullaway:nullaway:0.10.13-SNAPSHOT.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/com/uber/nullaway/nullaway/0.10.13-SNAPSHOT/maven-metadata.xml
          - https://repo.maven.apache.org/maven2/com/uber/nullaway/nullaway/0.10.13-SNAPSHOT/nullaway-0.10.13-SNAPSHOT.pom
          - https://dl.google.com/dl/android/maven2/com/uber/nullaway/nullaway/0.10.13-SNAPSHOT/maven-metadata.xml
          - https://dl.google.com/dl/android/maven2/com/uber/nullaway/nullaway/0.10.13-SNAPSHOT/nullaway-0.10.13-SNAPSHOT.pom
        Required by:
            project :nullaway
```

This is the [relevant Gradle script](https://github.com/uber/NullAway/blob/01ee4d7667870d604cd226755aa24f82fe8593ec/nullaway/build.gradle#L69-L70), in the `dependencies` section:
```
    // This ends up being resolved to the NullAway jar under nullaway/build/libs
    nullawayJar "com.uber.nullaway:nullaway:$VERSION_NAME"
```

Somehow, updating the Gradle Maven Publish plugin breaks this trick for referring to the built jar of the current module.  I am not a Gradle expert and fully admit the above may be an invalid hack.  But it worked with the old version of the plugin :-)  Is this a bug in the plugin?  Is there a workaround?  Really appreciate the help.  Happy to provide more details if that'd be helpful.

**Comment by gabrielittner** [comment]
The issue seems to be a side effect from the [behavior change in 0.23.0](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/CHANGELOG.md#0230-2022-12-29) that we don't set `project.group` and `project.version` automatically anymore. When you add this to the linked build.gradle it works again:
```
group = property("GROUP")
version = property("VERSION_NAME")
```

Side note: The `javaSourcesJar` task in jar-infer-cli is now just called `sourcesJar`.
