### ISSUE TITLE
Support library projects with multiple artifacts

### ISSUE THREAD

**Issue by colinrtwhite** [vanniktech/gradle-maven-publish-plugin#65]
Hi, I was wondering if it's possible to support projects with multiple artifacts (e.g. a library project with extension modules)? Currently, you can only set a single artifact ID in gradle.properties. Thanks!

**Comment by vanniktech** [comment]
Nope. Currently not possible.

**Comment by colinrtwhite** [comment]
:+1: Would it be helpful if I created a PR to support this?

**Comment by vanniktech** [comment]
What's your use case?

**Comment by colinrtwhite** [comment]
I'm working on a library that has a base artifact and several extension modules that add functionality (think `com.squareup.retrofit2:retrofit` and `com.squareup.retrofit2:converter-moshi`).

**Comment by gabrielittner** [comment]
That is supported already. You can create `gradle.properties` files in your modules. See OkHttp for example https://github.com/square/okhttp/blob/master/okhttp/gradle.properties
https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/gradle.properties

**Comment by colinrtwhite** [comment]
@gabrielittner 🤦‍♂Thanks this is exactly what I was looking for.
