### ISSUE TITLE
Timeout on CreateStagingRepository

### ISSUE THREAD

**Issue by eygraber** [vanniktech/gradle-maven-publish-plugin#654]
I've been getting a bunch of timeouts on CreateStagingRepository. I'm guessing it's a sonatype issue, but figured I'd put it here just in case. 

```
A failure occurred while executing com.vanniktech.maven.publish.sonatype.CreateSonatypeRepositoryTask$CreateStagingRepository
   > timeout
```

**Comment by gabrielittner** [comment]
It seems to have been on the Sonatype side. We do have 2 Gradle properties to increase timeouts for creating and closing staging repositories https://vanniktech.github.io/gradle-maven-publish-plugin/central/#timeouts
