### ISSUE TITLE
Comparison to `gradle-nexus-publish-plugin`

### ISSUE THREAD

**Issue by sschuberth** [vanniktech/gradle-maven-publish-plugin#665]
The `README.md` has a nice [comparison](https://github.com/vanniktech/gradle-maven-publish-plugin?tab=readme-ov-file#advantages-over-maven-publish) to the `maven-publish` plugin, and I was wondering whether we could get something similar for https://github.com/gradle-nexus/publish-plugin to give (potential) users (like me) a guide which plugin to pick 😉

**Comment by gabrielittner** [comment]
From a quick look, all of the comparison points other than "Maven Central integration" also apply to the gradle-nexus plugin. The things that it can do over this plugin is that the nexus plugin also supports self hosted nexus repositories and ivy publishing.
