### ISSUE TITLE
Warning 'variant.getJavaCompile()' in Android modules

### ISSUE THREAD

**Issue by WellingtonCosta** [vanniktech/gradle-maven-publish-plugin#67]
I have a library that contains both Java and Android modules. When I execute the build task, I get the following message:

`WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.`

It occurs only in Android modules that contains `apply plugin: 'com.vanniktech.maven.publish'`

**Comment by vanniktech** [comment]
Fixed with the latest SNAPSHOT release. #46

**Comment by WellingtonCosta** [comment]
When will it comes in a release version?

**Comment by vanniktech** [comment]
Probably once #54 is fixed
