### ISSUE TITLE
In a sources JAR, code is nested in a "main" subdirectory

### ISSUE THREAD

**Issue by sschuberth** [vanniktech/gradle-maven-publish-plugin#674]
Even for a pure JVM (Kotlin) project, source code is nested inside a "main" directory inside the generated sources JARs. This is a difference when migration from a pure `maven-publish` / `signing` plugin solution.

So I'm wondering, is this intended? I'd get the point for a KMP project which has `commonMain`, `jvmMain` etc. sourse set, but for a pure JVM project it seems more reasonable to create the same sources JARs that other solutions would.

**Comment by gabrielittner** [comment]
We're using the default `kotlinSourcesJar` task that the Kotlin/JVM project creates when creating a publication. I assume they are reusing their implementation across project types. I suggest that you open a YouTrack ticket and if they change it it will automatically be reflected here as well.

**Comment by TomerAberbach** [comment]
Hey @vanniktech @gabrielittner, curious if you were aware of the apparent difference between [`kotlinSourcesJar` and `sourcesJar`](https://youtrack.jetbrains.com/issue/KT-54207/Kotlin-has-two-sources-tasks-kotlinSourcesJar-and-sourcesJar-that-archives-sources-to-the-same-artifact)?

I'm not actually sure what's correct here, but we received an issue on the OpenAI Java repo, which uses this plugin to publish, and the reporter claims that `kotlinSourcesJar`'s output directory structure prevents Eclipse from detecting the sources (see https://github.com/openai/openai-java/issues/447)

**Comment by sschuberth** [comment]
> the reporter claims that `kotlinSourcesJar`'s output directory structure prevents Eclipse from detecting the sources

If that's really the case, then maybe it's rather a bug in https://github.com/Kotlin/kotlin-eclipse?

**Comment by the-former-programmer** [comment]
Unfortunately my Google-fu isn't powerful enough to be able to find a specification that details what the sources jar's layout should be, so all I can say is - if you took a look at any other Java project that existed in the world prior to this, you'd see sources aren't nested under a main folder. Which is probably why Eclipse was successful in just defaulting to only attaching sources under the root.
As an example, take a look at Apache's common-lang.
https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.17.0/commons-lang3-3.17.0-sources.jar

I'm not using any Kotlin specific plugin in Eclipse as the project is not using Kotlin.

**Comment by sschuberth** [comment]
> if you took a look at any other Java project that existed in the world prior to this, you'd see sources aren't nested under a main folder.

Which makes sense for Java, as in contrast to Kotlin it's not multiplatform-capable. Or phrased the other way around: As Kotlin project can be multiplatform, with different sources per platform, another layer is needed to distinguish between these. That's my guess why it's different in Kotlin compared to Java.

**Comment by TomerAberbach** [comment]
Yeah, that does make sense...

I guess the weird thing is that from the user's perspective a JVM only Kotlin library looks like a Java library so it's weird for them to have to take Kotlin into account.

I wonder if the directory structure should be simplified in the JVM only case?

Anyway, I'm also happy to ask on the Eclipse repo if you think that makes more sense @sschuberth
