### ISSUE TITLE
The documentation still has references to ./gradlew publishAllPublicationsToMavenCentral

### ISSUE THREAD

**Issue by MV-GH** [vanniktech/gradle-maven-publish-plugin#682]
I had used this task but it seems like it doesn't exist anymore and has just become publish?

Is the documentation outdated of am I doing something wrong that I can't find that task?

**Comment by gabrielittner** [comment]
Are you updating from an old version? If yes you might need to explicitly enable Maven Central by calling a method in the DSL or setting a Gradle property https://vanniktech.github.io/gradle-maven-publish-plugin/central/#configuring-maven-central. The task is still the right one and if it doesn't exist then `publish` also wouldn't do what you want

**Comment by MV-GH** [comment]
I am not updating from a old version. I tried publishing but it didnt find the task. It did find the publish task. It did do a successfully publish not sure what it did at this point. The problem seems to be indeed that I was missing the `mavenPublising` DSL. Thx for the help

**Comment by gabrielittner** [comment]
Glad to hear that it works now. The updating was just an assumption because we used to enable this by default
