### ISSUE TITLE
Not compatible with Dokka 0.10.0

### ISSUE THREAD

**Issue by zach-klippenstein** [vanniktech/gradle-maven-publish-plugin#69]
[Dokka 0.10.0](https://github.com/Kotlin/dokka/releases/tag/0.10.0) merges the android plugin into the main plugin, so this plugin fails when it tries to apply the `dokka-android` plugin.

Error message looks like this:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':my_project'.
> Failed to apply plugin [id 'org.jetbrains.dokka-android']
   > Cannot add task 'dokka' as a task with that name already exists.
```

**Comment by vanniktech** [comment]
Do you mind creating a PR for this?

**Comment by zach-klippenstein** [comment]
Sure, are you ok with dropping support for previous versions, i.e. just changing the auto-applied plugin to the main dokka plugin?
