### ISSUE TITLE
Unable to publish .aar when `jvm` publication is included in Kotlin Multiplatform library

### ISSUE THREAD

**Issue by y9vad9** [vanniktech/gradle-maven-publish-plugin#705]
## Versions
Kotlin version: `1.9.20` – `2.0.0-Beta2`
Publish plugin version: `0.25.3` – `0.26.0`
Gradle version: `8.5`
## Description
I'm trying to publish my library with three targets: `js`, `jvm` and `android`, but `android` target is not publishing while `jvm` is included. When I remove `jvm` from the build, `android` target seems to be publishing normally.
<details>
<summary>build.gradle.kts</summary>

```kotlin
import org.jetbrains.kotlin.gradle.dsl.ExplicitApiMode

plugins {
    kotlin("multiplatform")
    id("com.android.library")
    id("com.vanniktech.maven.publish")
}

kotlin {
    jvm {
        testRuns.named("test") {
            executionTask.configure {
                useJUnitPlatform()
            }
        }
    }

    androidTarget()

    js {
        browser {
            commonWebpackConfig {
                cssSupport {
                    enabled.set(true)
                }
            }
        }
    }
    jvmToolchain(11)

    explicitApi = ExplicitApiMode.Strict
}


android {
    compileSdk = libs.versions.android.compile.sdk.get().toInt()
    namespace = "io.timemates.credentials"

    defaultConfig {
        minSdk = libs.versions.android.min.sdk.get().toInt()
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

mavenPublishing {
    coordinates(
        groupId = "io.timemates.credentials",
        artifactId = "credentials-manager",
        version = System.getenv("LIB_VERSION") ?: return@mavenPublishing,
    )

    pom {
       // ommited
    }
}

publishing {
    repositories {
        maven {
            name = "TimeMates"

            url = uri(
                "sftp://${System.getenv("SSH_HOST")}:22/${System.getenv("SSH_DEPLOY_PATH")}"
            )

            credentials {
                username = System.getenv("SSH_USER")
                password = System.getenv("SSH_PASSWORD")
            }
        }
    }
}
```
</details> 

### Steps to reproduce
1. Open project from [sources](https://github.com/timemates/credentials-storage-kt/tree/30fd1e41ea59097d96ac94c110d7b980fbf5c376).
2. Run `publishToMavenLocal`/ `publishAllPublicationsTo..` / `publish` (but needs configuration, result is the same)
3. Check maven local folder for `.aar`
_____
4. Remove jvm from build as a target
5. Publish again and check maven local folder

**Comment by gabrielittner** [comment]
You need to enable publishing for the Android target inside the Kotlin DSL: https://kotlinlang.org/docs/multiplatform-publish-lib.html#publish-an-android-library

We can add this directly to the plugin though so that it won't be needed anymore in the future.

**Comment by y9vad9** [comment]
> You need to enable publishing for the Android target inside the Kotlin DSL: https://kotlinlang.org/docs/multiplatform-publish-lib.html#publish-an-android-library
> 
> We can add this directly to the plugin though so that it won't be needed anymore in the future.

Oh, thanks. But yet no answer why does it work without `jvm` subsystem included 👀

**Comment by gabrielittner** [comment]
Maybe the Kotlin Multiplatform plugin automatically enables the Android publishing if there is no jvm target. Either way I'll add this in the next release so that it'll always work by default
