### ISSUE TITLE
`Cannot get stagingProfiles for account` or `Received status code 401 from server: Unauthorized`

### ISSUE THREAD

**Issue by admund** [vanniktech/gradle-maven-publish-plugin#720]
I'm trying to publish my lib to MavenCentral using the newest version of this plugin.

My configuration is relatively standard.
```
mavenPublishing {
//    publishToMavenCentral(SonatypeHost.DEFAULT)
// trying both
    publishToMavenCentral(SonatypeHost.S01)

    signAllPublications()

    coordinates("io.github.admund", "marketspecificui", "0.1.0-SNAPSHOT")
// trying both
//    coordinates("io.github.admund", "marketspecificui", "0.1.0")

    pom {
        name.set("MarketSpecificUI")
        description.set("The library is for helping manage market-specific resources for Android apps.")
        inceptionYear.set("2024")
        url.set("https://github.com/admund/MarketSpecificUI")
        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                distribution.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }
        developers {
            developer {
                id.set("admund")
                name.set("Adrian Gardian")
                url.set("https://github.com/admund")
            }
        }
        scm {
            url.set("https://github.com/admund/MarketSpecificUI")
            connection.set("scm:git:git://github.com/admund/MarketSpecificUI.git")
            developerConnection.set("scm:git:ssh://git@github.com/admund/MarketSpecificUI.git")
        }
    }
}
```

When I'm trying to publish a version with `-SNAPSHOT`, I'm getting:
```
Could not PUT 'https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/admund/marketspecificui/0.1.0-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
```
But without `-SNAPSHOT`, I'm getting:
```
Cannot get stagingProfiles for account <username>: 
```
What are those `stagingProfiles`?

I was trying both `SonatypeHost.DEFAULT` and `SonatypeHost.S01`, same errors.

I created an account here https://central.sonatype.com/, and I generated a username and password, which I put in `~/.gradle/gradle.properties`.

What should I do else? I'm wondering if this is a plugin issue or maybe a MavenCentral issue?

**Comment by gabrielittner** [comment]
The plugin doesn't support publishing directly central.sonatype.com yet and only support the legacy publishing through OSSRH. I'm planning to have support for this either this week or next.

**Comment by ScottPierce** [comment]
I'm encountering the same issue, so I appreciate the clarity. I'll wait for central.sonatype.com support. @gabrielittner Thanks!

**Comment by gabrielittner** [comment]
Took a while but #733 addresses this.

If you want to already try it out:
- change version of the plugin to `central-portal-SNAPSHOT`
- use `SONATYPE_HOST=CENTRAL_PORTAL` or `publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL, ...)`
- set the user name and password from your central portal user token like described in the existing docs

Notes:
- publishing snapshots is not supported for the central portal
- the build will currently not fail if the validations on the portal side fail after the upload succeeded

**Comment by afreakyelf** [comment]
Hi, I followed all the steps but i am facing this issue while publishing my android library
`Upload failed: {"error":{"message":"Authentication Failed"}}`

In my `gradle.properties` file, i used username and password as token generated from here https://central.sonatype.org/publish/publish-portal-maven/#credentials

**Comment by panpf** [comment]
1. First, to solve the 'Received status code 401 from server: Unauthorized' problem, you need to replace the username and password of mavenCentral with the username and password of token. This is because mavenCentral has upgraded its security policy and no longer allows the use of the username and password of the sonatype account to access the repository.
2. Secondly, to solve the 'Cannot get stagingProfiles for account <username>' problem, you need to use the token of each repository. If you want to publish to the s01 repository, you need to use the username and password of the token generated from `s01.oss.sonatype.org`; if you want to publish to central, you need to use the username and password of the token generated from `central.sonatype.com`. Be sure not to use the wrong one.

Token generation document:
* https://central.sonatype.org/publish/generate-token/
* https://central.sonatype.org/publish/generate-portal-token/

**Comment by sschuberth** [comment]
> 2\. Secondly, to solve the 'Cannot get stagingProfiles for account ' problem, you need to use the token of each repository.

I started to get this problem today, out of nothing, it was working last week, and credentials / token did not change. Is this expected, maybe due to some change on the Sonatype side?

**Comment by tonidero** [comment]
> > 2. Secondly, to solve the 'Cannot get stagingProfiles for account ' problem, you need to use the token of each repository.
> 
> I started to get this problem today, out of nothing, it was working last week, and credentials / token did not change. Is this expected, maybe due to some change on the Sonatype side?

Same here. Worked last week, didn't change credentials nor any relevant changes on our side

**Comment by sschuberth** [comment]
Ok, what worked for me was to reset and recreate the user token at https://oss.sonatype.org/ and replace my old tokens with the new ones 👍🏻

**Comment by gabrielittner** [comment]
Just to confirm: When you publish through https://oss.sonatype.org/ or https://s01.oss.sonatype.org/ you need to create your user token through those sites. The interface looks like this:
![Screenshot 2024-07-18 at 12 50 26](https://github.com/user-attachments/assets/0ef8951a-3f7b-4c72-a7a1-7ad63c9ce060)

The token from central.sonatype.com only works when publishing through the central portal (when you have `publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)` or `SONATYPE_HOST=CENTRAL_PORTAL`), which is only available for now to new accounts.

**Comment by sschuberth** [comment]
> you need to create your user token through those sites.

Right, but my point was that I had created my previous token already through https://oss.sonatype.org/, but it stopped working for some reason, and I had to create another token to replace my previous one.

**Comment by sschuberth** [comment]
> [sschuberth](https://github.com/sschuberth) are you good now?

Yes, my release was successfully published.

**Comment by Yeboahmedia** [comment]
> > [sschuberth](https://github.com/sschuberth) are you good now?
> 
> Yes, my release was successfully published.

Thanks @sschuberth .. we tried your solution of resetting the tokens, and it worked.
