### ISSUE TITLE
Support Sonatype Portal Publisher API

### ISSUE THREAD

**Issue by eygraber** [vanniktech/gradle-maven-publish-plugin#722]
Looks like [Sonatype has a new API in preview for publishing](https://central.sonatype.org/publish/publish-portal-api/).

**Comment by sschuberth** [comment]
Also see https://github.com/GradleUp/nmcp.

**Comment by gabrielittner** [comment]
I've took a look at it last weekend and I'm planning to have an initial implementation done either this week or next.

**Comment by gabrielittner** [comment]
Took a while but #733 addresses this.

If you want to already try it out:
- change version of the plugin to `central-portal-SNAPSHOT`
- use `SONATYPE_HOST=CENTRAL_PORTAL` or `publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL, ...)`
- set the user name and password from your central portal user token like described in the existing docs

Notes:
- publishing snapshots is not supported for the central portal
- the build will currently not fail if the validations on the portal side fail after the upload succeeded
