### ISSUE TITLE
Is there a way to specify source code publish flag according to the targets?

### ISSUE THREAD

**Issue by yashctn88** [vanniktech/gradle-maven-publish-plugin#743]
Is there a way to specify source code publish flag according to the targets? Like for example i am publishing kotlin multi platform library and i want for some specific target only to generated source jars not for all. Can this be configured ?

Here is my configuration, because 

configure(
        com.vanniktech.maven.publish.KotlinMultiplatform(
            javadocJar = com.vanniktech.maven.publish.JavadocJar.Javadoc(),
            sourcesJar = false,
            androidVariantsToPublish = listOf("release")
        )
    )

The reason that i want to publish sources for specific target os that if i dont publish the source jar its getting rejected in the central.sonatype publish validation the sources are required 

<img width="692" alt="publish" src="https://github.com/vanniktech/gradle-maven-publish-plugin/assets/151529947/8a0505bc-af42-4cad-a2ab-2645bbba01a3">

**Comment by rvenky125** [comment]
how it's worked for you, I mean for me the ios and android targets are not uploading. It's uploading only the library only.

**Comment by rvenky125** [comment]
please help me

**Comment by gabrielittner** [comment]
@yashctn88 What is your reason for only wanting to publish sources only for some targets? Having a sources jar is a requirement of maven central so there isn't much that can be done. The [Kotlin Multiplatform plugin does have an API](https://kotlinlang.org/docs/multiplatform-publish-lib.html#disable-sources-publication) to disable the sources publication on a per target basis. You can try calling that after your `configure(com.vanniktech.maven.publish.KotlinMultiplatform(...))` call but the maven central requirement should still fail in that case.

@rvenky125 Please open a separate issue and include more information like your build configuration or a link to your project.

**Comment by rvenky125** [comment]
@gabrielittner Thanks for the reply, my issue resolved by using
``./gradlew clean publish --no-daemon --no-parallel --no-configuration-cache``
the android and ios components are not uploading with the below command.
``./gradlew publishKotlinMultiplatformPublicationToMavenCentralRepository --no-configuration-cache``.
if it's not intented then I'll create new issue, please let me know. Thank you.
