### ISSUE TITLE
In memory GPG key

### ISSUE THREAD

**Issue by grahamdaley** [vanniktech/gradle-maven-publish-plugin#745]
To generate the secring.gpg file when using gpg version 2.1 or later, use:

`gpg --export-secret-keys -o ~/.gnupg/secring.gpg`

**Comment by gabrielittner** [comment]
Is this a question or a suggestion?

**Comment by grahamdaley** [comment]
Just a suggestion. You might like to add it to your instructions here: https://vanniktech.github.io/gradle-maven-publish-plugin/central/#in-memory-gpg-key

**Comment by gabrielittner** [comment]
Thanks. I've updated the docs but went with a slightly different route (you don't need to write a secring.gpg you can just export directly)
