### ISSUE TITLE
Disable signing for specific tasks

### ISSUE THREAD

**Issue by tamimattafi** [vanniktech/gradle-maven-publish-plugin#746]
Hello! 
Thank you for this amazing plugin! It saves a lot of work and time with its seamless integration!

We use `mavenLocal` very often to test libraries in real environment before making a publication, and for that we don't need to sign artifacts, so we just disable this step temporarily by commenting configuration like this:
```kotlin
// signAllPublications()
```

However, sometimes we forget about this until the CI servers points that out, or sonatype declines our bundle, so we are wondering, is there a way to disable signing for specific publish tasks, let's say for `publishToMavenLocal`?

**Comment by michpohl** [comment]
Hi, I don't think you need anything from the plugin here to get what you need. Here's an example how you can exclude publishing to `mavenLocal` from signing (using Kotlin DSL):
```kotlin
            if (!project.gradle.startParameter.taskNames.any { it.contains("publishToMavenLocal") }) {
                signAllPublications()
            }
```

**Comment by gabrielittner** [comment]
@michpohl is the right way to go, however I'd use a property to enable/disable it. 

If you're using `com.vanniktech.maven.publish` you can also enable signing with the `RELEASE_SIGNING_ENABLED` Gradle property instead of doing it through the DSL.

**Comment by tamimattafi** [comment]
@michpohl Thank you for the tips!

@gabrielittner Yes, I'm using `com.vanniktech.maven.publish`, RELEASE_SIGNING_ENABLED property is what I was looking for. Is there an example on how to do it correctly? 

Here's how I tried doing it (after applying the plugin):
```kotlin
mavenPublishing.apply {
    // ...
    project.setProperty("RELEASE_SIGNING_ENABLED", true)
    // ...
}
```

This throws the following error:
```kotlin
Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'RELEASE_SIGNING_ENABLED' for project :library
```
