### ISSUE TITLE
Upload failed: {"error":{"message":"Authentication Failed"}}

### ISSUE THREAD

**Issue by afreakyelf** [vanniktech/gradle-maven-publish-plugin#749]
Hi, I followed all the steps but i am facing this issue while publishing my android library
`Upload failed: {"error":{"message":"Authentication Failed"}}`

In my `gradle.properties` file, i used username and password as token generated from here https://central.sonatype.org/publish/publish-portal-maven/#credentials

**Comment by lita-kornilova-comodule** [comment]
@afreakyelf I had the same issue yesterday, but it works today, so seems like a problem on Maven's side. Could you try again and see if anything changed?

**Comment by mrajatttt** [comment]
Sure will try. Just confused on credentials, @lita-kornilova-comodule do you mind sharing your build file and the way you are generating and signing. ofc, hide credentials :D

**Comment by afreakyelf** [comment]
lol nvm, it worked today.

**Comment by afreakyelf** [comment]
lol nvm, it worked today.

**Comment by afreakyelf** [comment]
Hi @vanniktech, I am successfully able to run the command `./gradlew publishAllPublicationsToMavenCentralRepository
` but in the central Sonatype portal, I am getting these issues. Can someone please help.

![image](https://github.com/vanniktech/gradle-maven-publish-plugin/assets/38572147/5e28720d-e4a3-48cc-90e0-e2e08b47db03)

my `gradle.properties` 

![image](https://github.com/vanniktech/gradle-maven-publish-plugin/assets/38572147/6b8c2741-3039-442c-85c4-f9ed3d3ac2b3)

I tried same in build.gradle.kts as well, still facing same issue.

**Comment by vanniktech** [comment]
Can you try without the `v` so use 2.0.92

**Comment by gabrielittner** [comment]
If removing the `v` doesn't work, could you download the `.pom` file from the "Component Files" section in the central portal and share it here?

**Comment by afreakyelf** [comment]
still getting the same error

![image](https://github.com/vanniktech/gradle-maven-publish-plugin/assets/38572147/ad383de9-9f7c-4cdd-b00a-b0cdfba57acd)

I tried to download the file but facing this issue
![image](https://github.com/vanniktech/gradle-maven-publish-plugin/assets/38572147/defe0fa1-35e9-4c69-9ecc-50953616584e)

So here is my local pom i believe
![image](https://github.com/vanniktech/gradle-maven-publish-plugin/assets/38572147/0f892469-e247-4aad-8ec8-6ea8cf342cf6)

**Comment by gabrielittner** [comment]
Could you share the full pom file and maybe push a branch with the Gradle publishing setup in your repo?

**Comment by afreakyelf** [comment]
Hey there you go, this branch has all maven publishing changes. Thank you
https://github.com/afreakyelf/Pdf-Viewer/tree/test-build

**Comment by gabrielittner** [comment]
It seems like Gradle won't properly add dependencies where the version comes from a bom to the generated pom.

So this:
```
    // compose
    implementation(platform("androidx.compose:compose-bom:2023.10.01"))
    androidTestImplementation(platform("androidx.compose:compose-bom:2023.10.01"))
    implementation("androidx.compose.ui:ui")
    // Android Studio Preview support
    implementation("androidx.compose.ui:ui-tooling-preview")
    debugImplementation("androidx.compose.ui:ui-tooling")
```
will cause the pom to contain
```
    <dependency>
      <groupId>androidx.compose.ui</groupId>
      <artifactId>ui</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>androidx.compose.ui</groupId>
      <artifactId>ui-tooling-preview</artifactId>
      <scope>runtime</scope>
    </dependency>
```
and maven central rejects that because it requires each dependency to have a version.

So the quickest fix is to explicitly give those 2 dependencies a version in your build file. I'll see if there is something we can do from this plugin to fix this automatically, but I'm not sure if this is possible

**Comment by afreakyelf** [comment]
It worked. Thanks alot!
