### ISSUE TITLE
Gradle 6+: maven plugin has been deprecated, use maven-publish plugin instead

### ISSUE THREAD

**Issue by akarnokd** [vanniktech/gradle-maven-publish-plugin#75]
As with almost every major Gradle update, there is again a plugin deprecated and will be removed the next major release.

Is there a way `gradle-maven-publish-plugin` can upgrade to `maven-publish`?

**Comment by gabrielittner** [comment]
You can try out
```
mavenPublish {
	useMavenPublish = true
}
```
to switch to the new plugin. I'm not sure how well it's working, but in theory it should. Maybe I can take a look soon to finish the implementation (Android is missing) and properly test it.

**Comment by gabrielittner** [comment]
In the lastest 0.9.0 snapshots the option was renamed to `useLegacyMode` (defaults to true, set to false to use maven-publish) and Android support was added. Our integration tests also now cover this mode to ensure that the output is the same.

To use ne non deprecated `maven-publish` plugin set this:
```
mavenPublish {
	useLegacyMode = false
}
```

**Comment by vanniktech** [comment]
This, we can also close, right?

**Comment by akarnokd** [comment]
Thanks.

**Comment by vanniktech** [comment]
If something isn't working, feel free to create an issue
