### ISSUE TITLE
Java8 Support

### ISSUE THREAD

**Issue by Speiger** [vanniktech/gradle-maven-publish-plugin#752]
o/
I am writing a library that has multiple releases for projects from java8 -> java22

And I am currently using your plugin to publish to maven central.
It has a hard coded requirement to be java10 or newer, which I can understand, but for multi releases that are optionally dynamic this is not easily dealt with.

(My solution is to disable your code in the public repo and just enable it when i want to publish)

I know this is a pretty selfish request, so I don't expect it, but I thought asking nicely wouldn't hurt ^^"

Thank you for reading.

**Comment by gabrielittner** [comment]
The plugin itself requires running on Java 11+ but you can still build and publish a library that targets older java releases. Gradle offers many mechanisms for that, like setting the [release option](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:release) or [toolchains](https://docs.gradle.org/current/userguide/toolchains.html) if you want the compile task to run with a specific JDK version.
