### ISSUE TITLE
Missing optional properties may produce literal nulls in output

### ISSUE THREAD

**Issue by koral--** [vanniktech/gradle-maven-publish-plugin#76]
Coming from that issue: https://github.com/mikepenz/AboutLibraries/issues/461 through another one https://github.com/square/okhttp/issues/5683 it turns out that if `POM_DESCRIPTION` is not set (I haven't found that in okhttp 4.x sources) then string with content `"null"` is produced in POM instead of not adding anything at all. Okhttp uses this plugin: https://github.com/square/okhttp/blob/master/okhttp/build.gradle#L1

I haven't tried to reproduce this nor further investigate if issue is located here or maybe in underlying Gradle implementation since my original issue at AboutLibraries has gone. I filled this issue because maybe someone else will be interested in investigation.

**Comment by gabrielittner** [comment]
Thanks for the report. It's fixed now.
