### ISSUE TITLE
publishing to Maven Central via the Portal Publisher API

### ISSUE THREAD

**Issue by drernie** [vanniktech/gradle-maven-publish-plugin#769]
Am I correct in inferring that the current version of this plugin does NOT use the new "[Central Publishing Portal API](https://central.sonatype.org/publish/publish-portal-api/)"?

The current [documentation page](https://vanniktech.github.io/gradle-maven-publish-plugin/central/) appears to point to the outdated "issues" page associated with the older system:

In particular, there seems to be a [secondary plugin](https://github.com/GradleUp/nmcp) that adds that missing functionality to this project:

> To configure the publications, you can use [vanniktech/gradle-maven-publish-plugin](https://github.com/vanniktech/gradle-maven-publish-plugin/) and call nmcp `publishAllPublicationsToCentralPortal` instead of vanniktech `publishAndReleaseToMavenCentral`.

Is that still needed?

**Comment by drernie** [comment]
FYI, the announcement that deprecated the old system was on Jan 9th of this year:

> On Jan 9th, 2024 [we announced](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/) issues.sonatype.org will be decommissioned soon. As part of the decommissioning process we removed the access to issues.sonatype.org, and we replaced our Jira ticketing system with a Zendesk email intake method

**Comment by gabrielittner** [comment]
The prerequisites section of the docs needs to be updated but the plugin does support the new central portal. To use the central portal for publishing simply use the `CENTRAL_PORTAL` option as described [here](https://vanniktech.github.io/gradle-maven-publish-plugin/central/#configuring-maven-central)

**Comment by gabrielittner** [comment]
The docs have been updated.

**Comment by drernie** [comment]
Sweet! Thank you so much.
