### ISSUE TITLE
Cannot perform signing task ':lib:signMavenPublication' because it has no configured signatory

### ISSUE THREAD

**Issue by drernie** [vanniktech/gradle-maven-publish-plugin#776]
Sorry, me [again](https://github.com/vanniktech/gradle-maven-publish-plugin/issues/772).

With your help, I _think_ I've configured my [build.gradle](https://github.com/quiltdata/quiltcore-java/blob/be5e92327a9a9f55a59899b0c5fb27b719a65a29/lib/build.gradle) file correctly. 

However, when I try to run `./gradlew publish` I get:

```log
Execution failed for task ':lib:signMavenPublication'.
> Cannot perform signing task ':lib:signMavenPublication' because it has no configured signatory
```

My gradle.properties file looks like:

```properties
mavenCentralUsername=user@example.com
mavenCentralPassword="op://Example/9Jz5z6Qzg7z6X3h0qz4z6/password"

signing.keyId=DEADBEEF
signing.password=MyLongPassword
signing.secretKeyRingFile=/Users/whatever/.gnupg/secring.gpg
```

(I originally had the long instead of eight-character `keyId`).

My understanding from [this ticket](https://github.com/vanniktech/gradle-maven-publish-plugin/issues/773) (and other examples) is that everything should "just work."  Any suggestions?

**Comment by drernie** [comment]
FYI, I tried using:

```groovy
signing {
	useGpgCmd()
	sign publishing.publications
}
```

Unfortunately, this never seemed to accept my `signing.password`; and I assume is not what was intended anyway.

I did verify that the password DID work for manually signing files. However, I could not figure out how to verify that `secring.gpg` was configured correctly.

**Comment by drernie** [comment]
For extra confusion, I feel like I may have had *some* configuration that got past the above error, only to fail with:

```log
Failed to stop service 'sonatype-repository-build-service'. 
> Cannot query the value of this property because it has no value available.
```

**Comment by drernie** [comment]
References I checked:

* https://docs.gradle.org/current/userguide/signing_plugin.html
* https://stackoverflow.com/questions/68447837/gradle-signing-android-library-publications-cannot-perform-signing-task-because
* [Provide Credentials API for in memory keys signing plugin](https://github.com/gradle/gradle/issues/16056)  
* https://github.com/vanniktech/gradle-maven-publish-plugin/blob/cb3398eded33bdd2779a3a39ee3ef1add00eeb7f/plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt#L135
*

**Comment by drernie** [comment]
Ah.  Looks like the problem is with my `~/.gradle/gradle.properties` file.  If I pass the parameters on the CLI, I get a different error.

```
Execution failed for task ':lib:signMavenPublication'.
> org.bouncycastle.openpgp.PGPException: checksum mismatch at 0 of 20
```

**Comment by drernie** [comment]
Doh! For some reason, THIS works:

```
~/.gradle/gradle.properties
```

But THIS did not:

```
./.gradle/gradle.properties
```

DOH! I guess it actually needed to be in `PROJECT_ROOT`, not `PROJECT_ROOT/.gradle`. I misread the documentation.

**Comment by drernie** [comment]
Now I (correctly?) get the:

```
Failed to stop service 'sonatype-repository-build-service'.
> Upload failed: {"error":{"message":"Invalid token"}}
```
But that's a seperate issue, so I will create a new ticket if I can't figure that out. Sorry for the thrash.

**Comment by drernie** [comment]
FYI, In case anyone cares I think I managed to get it to work.  The trick was to:

1. Generate an [API Token](https://central.sonatype.com/account) (rather than using the actual username/password for the Portal)
2. Use the "bare" password (rather than the "op:/User/..." wrapper I somehow got instead

**Comment by AndroidPoet** [comment]
Hi @drernie,
I am still getting the same error. How did you fix this? I am confused about the second setup. Are you referring to the token password obtained from the central portal or the secring.gpg path as a normal password?
