### ISSUE TITLE
How to use plugin on Github Actions?

### ISSUE THREAD

**Issue by iRYO400** [vanniktech/gradle-maven-publish-plugin#785]
Hello! I tried to use it according to the table of variables for CI from [docs](https://vanniktech.github.io/gradle-maven-publish-plugin/central/#__tabbed_5_2)

But it doesn't work, even if I run locally. 

So I switched to `signingInMemoryKeyId` from the source and tried to use them at least it runs locally, but Github Actions has its own [requirements](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-development-environment-secrets-for-your-repository-or-organization) like:

> Secret names are not case-sensitive.

It just switches to `SIGNINGINMEMORYKEYID` and plugin can't recognize them.

Please, help

**Comment by gabrielittner** [comment]
The name of the Github Actions secret does not need to match the name we require in the plugin. For example in this project the secret we're using for `signingInMemoryKey` is called `SIGNING_PRIVATE_KEY`: https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/.github/workflows/publish-release.yml#L41-L42

**Comment by iRYO400** [comment]
Thank you. It looks like I have a gap in my knowledge

**Comment by ddxv** [comment]
> The name of the Github Actions secret does not need to match the name we require in the plugin. For example in this project the secret we're using for `signingInMemoryKey` is called `SIGNING_PRIVATE_KEY`: https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/.github/workflows/publish-release.yml#L41-L42

Ah, glad you linked to this! I was looking around for a plugin for publishing via GitHub actions and wasn't sure if this one would work OK there. You might want to add that to the documentation (if this is an intended use case).
