### ISSUE TITLE
New sonatype credential system breaks staging profiles resolution

### ISSUE THREAD

**Issue by ZacSweers** [vanniktech/gradle-maven-publish-plugin#794]
Currently staging profiles resolution assumes the username is the staging profile, but with sonatype's new credential/token system, the username is a randomly generated string and not the name of the staging profile name. It looks like we need a separate property to specify the sonatype username manually still separate from auth

**Comment by gabrielittner** [comment]
I've just gave it a try and it worked for me. What's the error that you are seeing? Did you get the credentials from this page?
<img width="915" alt="Screenshot 2024-06-19 at 20 27 47" src="https://github.com/vanniktech/gradle-maven-publish-plugin/assets/1358105/93942959-5889-45ff-85ed-7dd4be4561cb">

**Comment by ZacSweers** [comment]
Seems to be working now, it appears that tokens generated from the regular sonatype UI are not usable with the oss.sonatype system
