### ISSUE TITLE
Help publishing after sonatype updates

### ISSUE THREAD

**Issue by ftomassetti** [vanniktech/gradle-maven-publish-plugin#805]
Hi,
I can publish to sonatype using other gradle plugins, but not in projects using this one.

Now, I have two pairs of credentials: my username and password, and the new pair associated to the token (so a different username and a token, to be used as a password).

In a project using the traditional plugin I could publish specifying:
```
publishing {

    repositories {
        maven {
            def releaseRepo = "https://oss.sonatype.org/service/local/staging/deploy/maven2/"
            def snapshotRepo = "https://oss.sonatype.org/content/repositories/snapshots/"
            url = isReleaseVersion ? releaseRepo : snapshotRepo
            credentials {
                username = project.hasProperty('ossrhTokenUsername') ? ossrhTokenUsername : "Unknown user"
                password = project.hasProperty('ossrhTokenPassword') ? ossrhTokenPassword : "Unknown password"
            }
        }
    }
   ...
``` 

In projects using this plugin, I am not sure how to specify the credentials. I guess they are coming from `~/.gradle/gradle.properties` and that I should set `mavenCentralUsername` and `mavenCentralPassword`.
The problem is that:
- If I leave the original values I can create the staging repository, but then upload fail
- If I use the "token" values (both username and password) then I cannot create the staging repository

Failure with the original credentials:
```
* What went wrong:
Execution failed for task ':lionweb-java-release:lionweb-java-release:core:publishMavenPublicationToMavenCentralRepository'.
> Failed to publish publication 'maven' to repository 'mavenCentral'
   > Could not PUT 'https://s01.oss.sonatype.org/service/local/staging/deployByRepositoryId/iolionweb-1108/io/lionweb/lionweb-java/lionweb-java-2023.1-core/0.2.17/lionweb-java-2023.1-core-0.2.17.jar'. Received status code 401 from server: Content access is protected by token
```

Failure when I use the new credentials:
```
* What went wrong:
Execution failed for task ':lionweb-java-release:lionweb-java-release:core:createStagingRepository'.
> A failure occurred while executing com.vanniktech.maven.publish.sonatype.CreateSonatypeRepositoryTask$CreateStagingRepository
   > Cannot get stagingProfiles for account <HERE THE USERNAME ASSOCIATED TO THE TOKEN IS PRINTED>: (401) 
```

Do you have any idea on how I should fix this?

**Comment by ftomassetti** [comment]
Oh... I just realized I have different tokens for oss.sonatype and s01.oss.sonatype... and I should use a different pair here.

**Comment by weihao-statsig** [comment]
Hi @ftomassetti , What do you mean by different tokens ? How to generate them ?

**Comment by ftomassetti** [comment]
With the same users I have different tokens on oss.sonatype.org (see https://oss.sonatype.org/#profile;Summary) and s01.oss.sonatype.org (https://s01.oss.sonatype.org/#profile;Summary).

Using the link I shared you should be able to create or get your token credentials

**Comment by weihao-statsig** [comment]
ohh, I see, Thanks! I encountered the same issue as this post, I can publish using the traditional plug-in, but not with this repo's plug in. How you figured out at last and make things work? For me, I think our project only has s01 type, and I've changed the mavenUsername and mavenPassword to use the new generated user token, but still not there.,

**Comment by ftomassetti** [comment]
Sorry @weihao-statsig I cannot think of anything else I changed to publish with this plugin
