### ISSUE TITLE
(discussion) Publishing only part of modules via this plugin. 

### ISSUE THREAD

**Issue by eirnym** [vanniktech/gradle-maven-publish-plugin#806]
I have a module tree and I'd like to publish only some of modules. How can I achieve this without information duplication? Does specification on parent module will automatically publish it's children?

Let's say I have following structure and I'd like to publish only modules `:modules:parent-1:child-1`, `:modules:parent-1:child-2`, `:modules:parent-1:parent-2` **without** `:modules:parent-1` and `:modules`

```
:modules:parent-1
:modules:parent-1:child-1
:modules:parent-1:child-2
:modules:parent-2
```

**Comment by gabrielittner** [comment]
The plugin will only publish the modules that it has been applied to. It does not automatically publish child modules.
