### ISSUE TITLE
Pom packaging is  not written

### ISSUE THREAD

**Issue by gabrielittner** [vanniktech/gradle-maven-publish-plugin#82]
It's only written for Android libraries in legacy mode. I guess that AGP adds it there. The one set through this plugin never makes it to the pom file. 

Example https://repo.maven.apache.org/maven2/com/vanniktech/gradle-maven-publish-plugin/0.8.0/gradle-maven-publish-plugin-0.8.0.pom

**Comment by ZacSweers** [comment]
This prevents us from using the non-legacy mode in 0.9.0 as well on https://github.com/slackhq/keeper

**Comment by gabrielittner** [comment]
@ZacSweers For non Android projects it's also broken in non legacy mode. From a very cursory check it didn't even work with the Chris Bane's script 4 years ago. https://repo.maven.apache.org/maven2/com/slack/keeper/keeper/0.2.0/keeper-0.2.0.pom

**Comment by gabrielittner** [comment]
Did you see any issues from not having it?

**Comment by ZacSweers** [comment]
yeah our upload fails pom validation on sonatype when we tried the new API. Memory is fuzzy but it was complaining about missing POM_URL and a number of other elements

**Comment by ZacSweers** [comment]
CC @jschear in case he remembers any other tidbits

**Comment by gabrielittner** [comment]
Ok, will take a look. I've got a theory what it might be.

**Comment by ZacSweers** [comment]
We'll try to do another repro and get a screenshot of the sonatype-reported errors

**Comment by gabrielittner** [comment]
It's fine. I've just tried it out locally and can see what's going wrong. Looks like we need some special configuration for gradle plugins.

**Comment by gabrielittner** [comment]
Closing this as packaging should come from the publication/component. For example Kotlin MPP sets the packaging for Kotlin/Native artifacts to `klib`.
