### ISSUE TITLE
Less agressive Kotlin version checks

### ISSUE THREAD

**Issue by vendelieu** [vanniktech/gradle-maven-publish-plugin#820]
Hello,

Firstly, I want to express my gratitude to you all for creating such a useful plugin!

However, I encountered an issue due to the method your Kotlin minimum version check. 
Specifically, I am implementing a compact publishing logic within `buildSrc` for reuse purposes.

Nonetheless, owing to this particular [check](https://github.com/vanniktech/gradle-maven-publish-plugin/blame/da599468864f7be7f0c694f174baa797ba8bf189/plugin/src/main/kotlin/com/vanniktech/maven/publish/ProjectExtensions.kt#L54), I received the following error:
![image](https://github.com/user-attachments/assets/99a44c92-02ee-4f65-91fe-a90d37776643)

My assumption is that this occurs because, within `buildSrc` the sources are not being provided, because below there's such remark:
`e: Please initialize at least one Kotlin target in 'project-name (:project)'.`

**Comment by vendelieu** [comment]
For those who have encountered a similar problem and can't find a solution, it may not be obvious but you need to add a kotlin gradle plugin:
```
org.jetbrains.kotlin:kotlin-gradle-plugin
```

The original issue was more about finding a different solution, not sure but it seems like gradle gives `project.pluginVersion()` or something like, maybe other solutions as well.

**Comment by gabrielittner** [comment]
Is the project that you're applying the publishing plugin to a Kotlin project? I'm asking because the Kotlin version check should only run if the project has `org.jetbrains.kotlin.jvm` or `org.jetbrains.kotlin.multiplatform` applied to it and in that case it expects the Kotlin Gradle plugin to be on the classpath. Unfortunately Gradle doesn't have an API to get the plugin version.

**Comment by vendelieu** [comment]
yeah, project have multiplatform plugin

**Comment by gabrielittner** [comment]
Then this is working as intended. The Kotlin plugin and the publish plugin need to be added to the same classloader which you achieved by adding the dependency.
