### ISSUE TITLE
JavaDoc JARs produced by publishToMavenLocal have incorrect names.

### ISSUE THREAD

**Issue by tommyettinger** [vanniktech/gradle-maven-publish-plugin#821]
Where all my other JARs have the expected names, such as `tantrum-digital-0.4.8.3.jar` and `tantrum-digital-0.4.8.3-sources.jar`, the JavaDoc JAR produced by publishToMavenLocal is called `maven-javadoc-0.4.8.3-javadoc.jar`, and I'm not sure what configuration can alter this. The project `tantrum-digital` is a subproject of `tantrum`, and I would prefer to configure this in the parent but it isn't required.

I first encountered this issue when updating from 0.25.3 to 0.29.0 . The issue seems like it may have been introduced here, https://github.com/vanniktech/gradle-maven-publish-plugin/commit/42d5235ab0cb697e13566c4cc91e44b7f69645b8

This issue doesn't occur when I configure the subproject in its own Gradle file, but it does occur when configured from a parent Gradle file. It also didn't occur in version 0.25.3 of this plugin. I'm using Windows 11, and running Gradle 8.9 with Java 17.

For now I will just configure from inside each of the (several) subprojects.

**Comment by tommyettinger** [comment]
Oh, and my repro case is here, https://github.com/tommyettinger/tantrum/commit/7a81f05e8ebbcc615e41e3ee5481101bc08f62a6 -- I just tried to build tantrum-regexodus (only updating the version to ensure it builds), and because it hasn't received the fix that tantrum-digital did in that commit, it outputs a JavaDoc JAR with the name `maven-javadoc-0.1.15.3-javadoc.jar` instead of the expected `tantrum-regexodus-0.1.15.3-javadoc.jar` .

**Comment by StefanBratanov** [comment]
Facing the same issue (no parent gradles) so resorted to your workaround:

```
// https://github.com/vanniktech/gradle-maven-publish-plugin/issues/821
mavenPlainJavadocJar.archiveBaseName.set("${project.name}")
```

For reference: https://github.com/Consensys/jc-kzg-4844/blob/master/build.gradle

**Comment by portlek** [comment]
this is how i fix it
```kotlin
import com.vanniktech.maven.publish.tasks.JavadocJar

tasks.withType<JavadocJar> { afterEvaluate { archiveBaseName = name } }
```

**Comment by gabrielittner** [comment]
Thanks for the detailed report and the reproducers. Do you actually see the issue with the published artifacts or just in the build folder?

For example when I run `publishToMavenLocal` on https://github.com/tommyettinger/tantrum/commit/7a81f05e8ebbcc615e41e3ee5481101bc08f62a6 I see this in the build folder like you described:
```
tree tantrum-regexodus/build/libs/
tantrum-regexodus/build/libs/
├── maven-javadoc-1.0.0-javadoc.jar
├── maven-javadoc-1.0.0-javadoc.jar.asc
├── tantrum-regexodus-1.0.0-sources.jar
├── tantrum-regexodus-1.0.0-sources.jar.asc
├── tantrum-regexodus-1.0.0.jar
└── tantrum-regexodus-1.0.0.jar.asc
```
However looking at maven local, the jar has the correct name:
```
tree ~/.m2/repository/com/github/tommyettinger/ | grep javadoc.jar
│   │   ├── tantrum-1.0.0-javadoc.jar
│   │   ├── tantrum-1.0.0-javadoc.jar.asc
│   │   ├── tantrum-digital-1.0.0-javadoc.jar
│   │   ├── tantrum-digital-1.0.0-javadoc.jar.asc
│   │   ├── tantrum-jdkgdxds-1.0.0-javadoc.jar
│   │   ├── tantrum-jdkgdxds-1.0.0-javadoc.jar.asc
│   │   ├── tantrum-libgdx-1.0.0-javadoc.jar
│   │   ├── tantrum-libgdx-1.0.0-javadoc.jar.asc
    │   ├── tantrum-regexodus-1.0.0-javadoc.jar
    │   ├── tantrum-regexodus-1.0.0-javadoc.jar.asc
```

Same for the project provided by @StefanBratanov after removing the workaround:
```
tree ~/.m2/repository/io/consensys/protocols/jc-kzg-4844/ | grep javadoc.jar
│   ├── jc-kzg-4844-UNKNOWN-javadoc.jar
│   ├── jc-kzg-4844-UNKNOWN-javadoc.jar.asc
```
```
tree build/libs/
build/libs/
├── jc-kzg-4844-UNKNOWN-javadoc.jar
├── jc-kzg-4844-UNKNOWN-javadoc.jar.asc
├── jc-kzg-4844-UNKNOWN-sources.jar
├── jc-kzg-4844-UNKNOWN-sources.jar.asc
├── jc-kzg-4844-UNKNOWN.jar
├── jc-kzg-4844-UNKNOWN.jar.asc
├── maven-javadoc-UNKNOWN-javadoc.jar
└── maven-javadoc-UNKNOWN-javadoc.jar.asc
```

If it's also limited to the build folder for you, is the naming an issue for you if it's limited to that?

**Comment by tommyettinger** [comment]
I was surprised by this, but the published artifacts aren't affected, and I don't know why. The issue is mostly for when I'm uploading JARs for a GitHub release. I've mostly got a workaround going in all my current code, which might be why tantrum isn't showing the issue now. The problem is mostly that `maven-javadoc-1.0.0-javadoc.jar` is used as the name for all subproject JARs, so they overwrite each other if they ever go into the same folder (or same GitHub release). My workaround code is per-project, and is approximately:

```gradle
import com.vanniktech.maven.publish.JavaLibrary
import com.vanniktech.maven.publish.JavadocJar

mavenPublishing {
    configure(new JavaLibrary(new JavadocJar.Javadoc(), true))
}

mavenPlainJavadocJar.archiveBaseName.set("$POM_NAME")
```

I sometimes set a `projectName` and use `mavenPlainJavadocJar.archiveBaseName.set(projectName)`, instead.

This isn't really a problem for me anymore, but it might be for other people who haven't discovered how to work around it yet. My build files would be cleaner with the earlier behavior that named javadoc jars like the other jars, and like they are in a Maven local installation, though.

**Comment by gabrielittner** [comment]
I've opened the linked PR to add the project name to the jar by default, so in your case it would for example be `tantrum-regexodus-maven-javadoc-1.0.0-javadoc.jar`. So not entirely the same as the default/old name but it makes name collisions less likely. Generally though for taking the jars I'd recommend taking them from maven local or publishing to a specific local folder because then Gradle takes care of naming them based on the publishing coordinates.
