### ISSUE TITLE
Multi-variant Android Library sources?

### ISSUE THREAD

**Issue by ianthetechie** [vanniktech/gradle-maven-publish-plugin#828]
I observed when debugging some libraries published with the new plugin that multi-variant libraries do not automatically download sources or documentation in IntelliJ.

I assumed that I had just overlooked something in my publishing config, but it looks like the doc and sources JARs are all there. Here's an example repository listing: https://repo.maven.apache.org/maven2/io/github/rallista/maplibre-compose/0.0.18/.

In the case of sources, Android Studio does not give any options / quick fixes. For docs, I do get a download prompt as shown below when hovering on an item in source:

<img width="402" alt="image" src="https://github.com/user-attachments/assets/bc3b072a-c4ae-4ef4-9783-0e3113c4c795">

However, clicking the button results an a cryptic gradle error:

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/a20efe8f-6af5-4751-891d-5429c21b2724">

I have a sneaking suspicion that this is related to the structure of the Android multi-variant library, but I frankly don't know enough to be sure. This looks at least somewhat related: https://medium.com/glovo-engineering/publishing-a-variant-aware-android-library-with-its-sources-c61387323963.

Any ideas?

**Comment by gabrielittner** [comment]
In Android Studio there is an experimental option to enable support for source jars of multi variant libraries:
<img width="872" alt="Screenshot 2024-09-19 at 19 48 30" src="https://github.com/user-attachments/assets/f9ba5334-595f-4492-9c03-9d079128f1bd">
More details can be found here: https://issuetracker.google.com/issues/197636221. I'm not sure if IntelliJ exposes a similar kind of option anywhere or whether it will only start supporting it when the Android plugin supports it by default.

**Comment by ianthetechie** [comment]
Hmmmm interesting... I tried enabling this, but it doesn't seem to have any effect.for my use cases :/

**Comment by gabrielittner** [comment]
Could you comment that on the Google issue tracker? From the publishing side everything looks fine. Unfortunately the whole multi variant publishing feature has been in this weird state ever since it was added.
