### ISSUE TITLE
Is Ability to publish Kotlin libraries from any host possible to use with the lib?

### ISSUE THREAD

**Issue by apolostudio** [vanniktech/gradle-maven-publish-plugin#877]
I was trying [https://kotlinlang.org/docs/whatsnew21.html#ability-to-publish-kotlin-libraries-from-any-host](https://kotlinlang.org/docs/whatsnew21.html#ability-to-publish-kotlin-libraries-from-any-host) using the library but ive found a weird error in sonatype saying `Cannot invoke "String.contains(java.lang.CharSequence)" because "pUrl" is null` and i dont know if its a problem with the feature or the plugin needs to be updated to kotlin 2.1.0 using in gradle.properties the flag `kotlin.native.enableKlibsCrossCompilation=true`.
Checking the logs doesnt seem theres an error in compiling the libs in linux [(githubActionLog)](https://github.com/apolostudio/squircle-shape/actions/runs/12166481237/job/33933707060#step:8:187) so maybe it smth related to the plugin.

**Comment by gabrielittner** [comment]
I haven't had the chance to test it yet, generally from the plugin side there shouldn't be anything speaking against it working.

> ive found a weird error in sonatype saying Cannot invoke "String.contains(java.lang.CharSequence)" because "pUrl" is null
Is this error on the Sonatype website? Does it have any other details?

**Comment by apolostudio** [comment]
yes its in the sonatype website, it was the only error
 that popped up
![Captura de pantalla 2024-12-05 154226](https://github.com/user-attachments/assets/850cea65-6d14-4b66-b72e-475be023e0b9)

**Comment by apolostudio** [comment]
sorry, my mistake. The publication version was coming from toml version file and the build.gradle was not accessing it correctly. Thats why string was null and throwing error. `publish Kotlin libraries from any host` is working just fine. Closing this
