### ISSUE TITLE
How to upload archives into Bintray?

### ISSUE THREAD

**Issue by anggrayudi** [vanniktech/gradle-maven-publish-plugin#98]
Actually I am confusing because this plugin does not provide documentation on how to upload JAR or AAR into Bintray. Does this plugin support uploading AAR & JAR into Bintray? If yes, can you provide us the documentation?

Thank you.

**Comment by gabrielittner** [comment]
Do you want to publish to your own internal bintray instance or is it an opensource project you want to publish?

**Comment by anggrayudi** [comment]
Open source library. You can check my library here:
https://github.com/anggrayudi/MaterialPreference

**Comment by gabrielittner** [comment]
I've never published to bintray before, in theory you just need to change the releaseRepositoryUrl as mentioned in the readme. I'd generally recommend publishing to Maven Central though (https://central.sonatype.org/pages/ossrh-guide.html#initial-setup). It's automatically mirrored by jcenter so you're library will be available on both.

**Comment by anggrayudi** [comment]
Ok, I will try it and report the result to you soon.

**Comment by gabrielittner** [comment]
I'm updating our readme in #100. Once you get to the deployment part of the link above you can just proceed with what's in the new readme.

**Comment by gabrielittner** [comment]
Thew new readme has been merged. I'm closing this issue for now, feel free to open more issues if you find any gaps in the documentation.
